-- ============================================
-- JubileeVerse Database Schema
-- Migration 019: Persona Response Tracking
-- ============================================

-- Add response_count column to personas table
-- This tracks total AI responses generated by each persona
ALTER TABLE personas ADD COLUMN IF NOT EXISTS response_count BIGINT DEFAULT 0;

-- Add tokens_used column to personas table
-- This tracks total tokens consumed by each persona
ALTER TABLE personas ADD COLUMN IF NOT EXISTS tokens_used BIGINT DEFAULT 0;

-- Create index for efficient sorting by response_count
CREATE INDEX IF NOT EXISTS idx_personas_response_count ON personas(response_count DESC);

-- Update the existing trigger function to also track persona responses
-- This modifies update_conversation_stats() from migration 004
CREATE OR REPLACE FUNCTION update_conversation_stats()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE conversations
    SET
        message_count = (
            SELECT COUNT(*)
            FROM messages
            WHERE conversation_id = NEW.conversation_id
            AND status = 'delivered'
        ),
        last_message_at = NOW(),
        updated_at = NOW()
    WHERE id = NEW.conversation_id;

    -- Increment persona usage count for user messages (existing behavior)
    IF NEW.role = 'user' THEN
        UPDATE personas
        SET usage_count = usage_count + 1
        WHERE id = (SELECT persona_id FROM conversations WHERE id = NEW.conversation_id);
    END IF;

    -- Increment persona response_count for assistant messages
    IF NEW.role = 'assistant' AND NEW.persona_id IS NOT NULL THEN
        UPDATE personas
        SET response_count = response_count + 1
        WHERE id = NEW.persona_id;
    END IF;

    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create a separate function to update persona tokens_used
-- This is called from the application when token usage is recorded
CREATE OR REPLACE FUNCTION increment_persona_tokens(
    p_persona_id UUID,
    p_tokens INT
)
RETURNS VOID AS $$
BEGIN
    UPDATE personas
    SET tokens_used = tokens_used + p_tokens
    WHERE id = p_persona_id;
END;
$$ language 'plpgsql';

-- Backfill response_count from existing messages
-- Count all assistant messages grouped by persona_id
DO $$
DECLARE
    rec RECORD;
BEGIN
    FOR rec IN
        SELECT persona_id, COUNT(*) as count
        FROM messages
        WHERE role = 'assistant' AND persona_id IS NOT NULL
        GROUP BY persona_id
    LOOP
        UPDATE personas
        SET response_count = rec.count
        WHERE id = rec.persona_id;
    END LOOP;
END $$;

-- Also update response_count from board messages (discussion boards)
DO $$
DECLARE
    rec RECORD;
BEGIN
    FOR rec IN
        SELECT persona_id, COUNT(*) as count
        FROM board_messages
        WHERE is_ai_response = TRUE AND persona_id IS NOT NULL
        GROUP BY persona_id
    LOOP
        UPDATE personas
        SET response_count = response_count + rec.count
        WHERE id = rec.persona_id;
    END LOOP;
END $$;
