-- Migration: Insert Genesis chapters 23-31 (ESV)
-- Book: Genesis (book_id: genesis, book_order: 1)

-- Chapter 23: Sarah's Death and Burial
INSERT INTO bible_verses (book_id, book_name, book_order, chapter_number, verse_number, verse_text, section_heading, translation_code)
VALUES
('genesis', 'Genesis', 1, 23, 1, 'Sarah lived 127 years; these were the years of the life of Sarah.', 'Sarah''s Death and Burial', 'ESV'),
('genesis', 'Genesis', 1, 23, 2, 'And Sarah died at Kiriath-arba (that is, Hebron) in the land of Canaan, and Abraham went in to mourn for Sarah and to weep for her.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 23, 3, 'And Abraham rose up from before his dead and said to the Hittites,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 23, 4, '"I am a sojourner and foreigner among you; give me property among you for a burying place, that I may bury my dead out of my sight."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 23, 5, 'The Hittites answered Abraham,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 23, 6, '"Hear us, my lord; you are a prince of God among us. Bury your dead in the choicest of our tombs. None of us will withhold from you his tomb to hinder you from burying your dead."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 23, 7, 'Abraham rose and bowed to the Hittites, the people of the land.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 23, 8, 'And he said to them, "If you are willing that I should bury my dead out of my sight, hear me and entreat for me Ephron the son of Zohar,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 23, 9, 'that he may give me the cave of Machpelah, which he owns; it is at the end of his field. For the full price let him give it to me in your presence as property for a burying place."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 23, 10, 'Now Ephron was sitting among the Hittites, and Ephron the Hittite answered Abraham in the hearing of the Hittites, of all who went in at the gate of his city,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 23, 11, '"No, my lord, hear me: I give you the field, and I give you the cave that is in it. In the sight of the sons of my people I give it to you. Bury your dead."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 23, 12, 'Then Abraham bowed down before the people of the land.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 23, 13, 'And he said to Ephron in the hearing of the people of the land, "But if you will, hear me: I give the price of the field. Accept it from me, that I may bury my dead there."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 23, 14, 'Ephron answered Abraham,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 23, 15, '"My lord, listen to me: a piece of land worth four hundred shekels of silver, what is that between you and me? Bury your dead."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 23, 16, 'Abraham listened to Ephron, and Abraham weighed out for Ephron the silver that he had named in the hearing of the Hittites, four hundred shekels of silver, according to the weights current among the merchants.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 23, 17, 'So the field of Ephron in Machpelah, which was to the east of Mamre, the field with the cave that was in it and all the trees that were in the field, throughout its whole area, was made over', NULL, 'ESV'),
('genesis', 'Genesis', 1, 23, 18, 'to Abraham as a possession in the presence of the Hittites, before all who went in at the gate of his city.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 23, 19, 'After this, Abraham buried Sarah his wife in the cave of the field of Machpelah east of Mamre (that is, Hebron) in the land of Canaan.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 23, 20, 'The field and the cave that is in it were made over to Abraham as property for a burying place by the Hittites.', NULL, 'ESV')
ON CONFLICT (book_id, chapter_number, verse_number, translation_code)
DO UPDATE SET verse_text = EXCLUDED.verse_text, section_heading = EXCLUDED.section_heading;

-- Chapter 24: Isaac and Rebekah
INSERT INTO bible_verses (book_id, book_name, book_order, chapter_number, verse_number, verse_text, section_heading, translation_code)
VALUES
('genesis', 'Genesis', 1, 24, 1, 'Now Abraham was old, well advanced in years. And the LORD had blessed Abraham in all things.', 'Isaac and Rebekah', 'ESV'),
('genesis', 'Genesis', 1, 24, 2, 'And Abraham said to his servant, the oldest of his household, who had charge of all that he had, "Put your hand under my thigh,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 3, 'that I may make you swear by the LORD, the God of heaven and God of the earth, that you will not take a wife for my son from the daughters of the Canaanites, among whom I dwell,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 4, 'but will go to my country and to my kindred, and take a wife for my son Isaac."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 5, 'The servant said to him, "Perhaps the woman may not be willing to follow me to this land. Must I then take your son back to the land from which you came?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 6, 'Abraham said to him, "See to it that you do not take my son back there.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 7, 'The LORD, the God of heaven, who took me from my father''s house and from the land of my kindred, and who spoke to me and swore to me, ''To your offspring I will give this land,'' he will send his angel before you, and you shall take a wife for my son from there.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 8, 'But if the woman is not willing to follow you, then you will be free from this oath of mine; only you must not take my son back there."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 9, 'So the servant put his hand under the thigh of Abraham his master and swore to him concerning this matter.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 10, 'Then the servant took ten of his master''s camels and departed, taking all sorts of choice gifts from his master; and he arose and went to Mesopotamia to the city of Nahor.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 11, 'And he made the camels kneel down outside the city by the well of water at the time of evening, the time when women go out to draw water.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 12, 'And he said, "O LORD, God of my master Abraham, please grant me success today and show steadfast love to my master Abraham.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 13, 'Behold, I am standing by the spring of water, and the daughters of the men of the city are coming out to draw water.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 14, 'Let the young woman to whom I shall say, ''Please let down your jar that I may drink,'' and who shall say, ''Drink, and I will water your camels''—let her be the one whom you have appointed for your servant Isaac. By this I shall know that you have shown steadfast love to my master."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 15, 'Before he had finished speaking, behold, Rebekah, who was born to Bethuel the son of Milcah, the wife of Nahor, Abraham''s brother, came out with her water jar on her shoulder.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 16, 'The young woman was very attractive in appearance, a maiden whom no man had known. She went down to the spring and filled her jar and came up.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 17, 'Then the servant ran to meet her and said, "Please give me a little water to drink from your jar."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 18, 'She said, "Drink, my lord." And she quickly let down her jar upon her hand and gave him a drink.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 19, 'When she had finished giving him a drink, she said, "I will draw water for your camels also, until they have finished drinking."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 20, 'So she quickly emptied her jar into the trough and ran again to the well to draw water, and she drew for all his camels.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 21, 'The man gazed at her in silence to learn whether the LORD had prospered his journey or not.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 22, 'When the camels had finished drinking, the man took a gold ring weighing a half shekel, and two bracelets for her arms weighing ten gold shekels,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 23, 'and said, "Please tell me whose daughter you are. Is there room in your father''s house for us to spend the night?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 24, 'She said to him, "I am the daughter of Bethuel the son of Milcah, whom she bore to Nahor."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 25, 'She added, "We have plenty of both straw and fodder, and room to spend the night."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 26, 'The man bowed his head and worshiped the LORD', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 27, 'and said, "Blessed be the LORD, the God of my master Abraham, who has not forsaken his steadfast love and his faithfulness toward my master. As for me, the LORD has led me in the way to the house of my master''s kinsmen."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 28, 'Then the young woman ran and told her mother''s household about these things.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 29, 'Rebekah had a brother whose name was Laban. Laban ran out toward the man, to the spring.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 30, 'As soon as he saw the ring and the bracelets on his sister''s arms, and heard the words of Rebekah his sister, "Thus the man spoke to me," he went to the man. And behold, he was standing by the camels at the spring.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 31, 'He said, "Come in, O blessed of the LORD. Why do you stand outside? For I have prepared the house and a place for the camels."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 32, 'So the man came to the house and unharnessed the camels, and gave straw and fodder to the camels, and there was water to wash his feet and the feet of the men who were with him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 33, 'Then food was set before him to eat. But he said, "I will not eat until I have said what I have to say." He said, "Speak on."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 34, 'So he said, "I am Abraham''s servant.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 35, 'The LORD has greatly blessed my master, and he has become great. He has given him flocks and herds, silver and gold, male servants and female servants, camels and donkeys.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 36, 'And Sarah my master''s wife bore a son to my master when she was old, and to him he has given all that he has.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 37, 'My master made me swear, saying, ''You shall not take a wife for my son from the daughters of the Canaanites, in whose land I dwell,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 38, 'but you shall go to my father''s house and to my clan and take a wife for my son.''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 39, 'I said to my master, ''Perhaps the woman will not follow me.''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 40, 'But he said to me, ''The LORD, before whom I have walked, will send his angel with you and prosper your way. You shall take a wife for my son from my clan and from my father''s house.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 41, 'Then you will be free from my oath, when you come to my clan. And if they will not give her to you, you will be free from my oath.''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 42, '"I came today to the spring and said, ''O LORD, the God of my master Abraham, if now you are prospering the way that I go,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 43, 'behold, I am standing by the spring of water. Let the virgin who comes out to draw water, to whom I shall say, "Please give me a little water from your jar to drink,"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 44, 'and who will say to me, "Drink, and I will draw for your camels also," let her be the woman whom the LORD has appointed for my master''s son.''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 45, '"Before I had finished speaking in my heart, behold, Rebekah came out with her water jar on her shoulder, and she went down to the spring and drew water. I said to her, ''Please let me drink.''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 46, 'She quickly let down her jar from her shoulder and said, ''Drink, and I will give your camels drink also.'' So I drank, and she gave the camels drink also.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 47, 'Then I asked her, ''Whose daughter are you?'' She said, ''The daughter of Bethuel, Nahor''s son, whom Milcah bore to him.'' So I put the ring on her nose and the bracelets on her arms.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 48, 'Then I bowed my head and worshiped the LORD and blessed the LORD, the God of my master Abraham, who had led me by the right way to take the daughter of my master''s kinsman for his son.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 49, 'Now then, if you are going to show steadfast love and faithfulness to my master, tell me; and if not, tell me, that I may turn to the right hand or to the left."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 50, 'Then Laban and Bethuel answered and said, "The thing has come from the LORD; we cannot speak to you bad or good.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 51, 'Behold, Rebekah is before you; take her and go, and let her be the wife of your master''s son, as the LORD has spoken."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 52, 'When Abraham''s servant heard their words, he bowed himself to the earth before the LORD.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 53, 'And the servant brought out jewelry of silver and of gold, and garments, and gave them to Rebekah. He also gave to her brother and to her mother costly ornaments.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 54, 'And he and the men who were with him ate and drank, and they spent the night there. When they arose in the morning, he said, "Send me away to my master."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 55, 'Her brother and her mother said, "Let the young woman remain with us a while, at least ten days; after that she may go."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 56, 'But he said to them, "Do not delay me, since the LORD has prospered my way. Send me away that I may go to my master."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 57, 'They said, "Let us call the young woman and ask her."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 58, 'And they called Rebekah and said to her, "Will you go with this man?" She said, "I will go."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 59, 'So they sent away Rebekah their sister and her nurse, and Abraham''s servant and his men.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 60, 'And they blessed Rebekah and said to her, "Our sister, may you become thousands of ten thousands, and may your offspring possess the gate of those who hate him!"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 61, 'Then Rebekah and her young women arose and rode on the camels and followed the man. Thus the servant took Rebekah and went his way.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 62, 'Now Isaac had returned from Beer-lahai-roi and was dwelling in the Negeb.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 63, 'And Isaac went out to meditate in the field toward evening. And he lifted up his eyes and saw, and behold, there were camels coming.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 64, 'And Rebekah lifted up her eyes, and when she saw Isaac, she dismounted from the camel', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 65, 'and said to the servant, "Who is that man, walking in the field to meet us?" The servant said, "It is my master." So she took her veil and covered herself.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 66, 'And the servant told Isaac all the things that he had done.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 24, 67, 'Then Isaac brought her into the tent of Sarah his mother and took Rebekah, and she became his wife, and he loved her. So Isaac was comforted after his mother''s death.', NULL, 'ESV')
ON CONFLICT (book_id, chapter_number, verse_number, translation_code)
DO UPDATE SET verse_text = EXCLUDED.verse_text, section_heading = EXCLUDED.section_heading;

-- Chapter 25: Abraham's Death and His Descendants
INSERT INTO bible_verses (book_id, book_name, book_order, chapter_number, verse_number, verse_text, section_heading, translation_code)
VALUES
('genesis', 'Genesis', 1, 25, 1, 'Abraham took another wife, whose name was Keturah.', 'Abraham''s Death and His Descendants', 'ESV'),
('genesis', 'Genesis', 1, 25, 2, 'She bore him Zimran, Jokshan, Medan, Midian, Ishbak, and Shuah.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 3, 'Jokshan fathered Sheba and Dedan. The sons of Dedan were Asshurim, Letushim, and Leummim.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 4, 'The sons of Midian were Ephah, Epher, Hanoch, Abida, and Eldaah. All these were the children of Keturah.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 5, 'Abraham gave all he had to Isaac.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 6, 'But to the sons of his concubines Abraham gave gifts, and while he was still living he sent them away from his son Isaac, eastward to the east country.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 7, 'These are the days of the years of Abraham''s life, 175 years.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 8, 'Abraham breathed his last and died in a good old age, an old man and full of years, and was gathered to his people.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 9, 'Isaac and Ishmael his sons buried him in the cave of Machpelah, in the field of Ephron the son of Zohar the Hittite, east of Mamre,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 10, 'the field that Abraham purchased from the Hittites. There Abraham was buried, with Sarah his wife.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 11, 'After the death of Abraham, God blessed Isaac his son. And Isaac settled at Beer-lahai-roi.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 12, 'These are the generations of Ishmael, Abraham''s son, whom Hagar the Egyptian, Sarah''s servant, bore to Abraham.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 13, 'These are the names of the sons of Ishmael, named in the order of their birth: Nebaioth, the firstborn of Ishmael; and Kedar, Adbeel, Mibsam,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 14, 'Mishma, Dumah, Massa,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 15, 'Hadad, Tema, Jetur, Naphish, and Kedemah.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 16, 'These are the sons of Ishmael and these are their names, by their villages and by their encampments, twelve princes according to their tribes.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 17, '(These are the years of the life of Ishmael: 137 years. He breathed his last and died, and was gathered to his people.)', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 18, 'They settled from Havilah to Shur, which is opposite Egypt in the direction of Assyria. He settled over against all his kinsmen.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 19, 'These are the generations of Isaac, Abraham''s son: Abraham fathered Isaac,', 'The Birth of Esau and Jacob', 'ESV'),
('genesis', 'Genesis', 1, 25, 20, 'and Isaac was forty years old when he took Rebekah, the daughter of Bethuel the Aramean of Paddan-aram, the sister of Laban the Aramean, to be his wife.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 21, 'And Isaac prayed to the LORD for his wife, because she was barren. And the LORD granted his prayer, and Rebekah his wife conceived.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 22, 'The children struggled together within her, and she said, "If it is thus, why is this happening to me?" So she went to inquire of the LORD.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 23, 'And the LORD said to her, "Two nations are in your womb, and two peoples from within you shall be divided; the one shall be stronger than the other, the older shall serve the younger."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 24, 'When her days to give birth were completed, behold, there were twins in her womb.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 25, 'The first came out red, all his body like a hairy cloak, so they called his name Esau.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 26, 'Afterward his brother came out with his hand holding Esau''s heel, so his name was called Jacob. Isaac was sixty years old when she bore them.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 27, 'When the boys grew up, Esau was a skillful hunter, a man of the field, while Jacob was a quiet man, dwelling in tents.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 28, 'Isaac loved Esau because he ate of his game, but Rebekah loved Jacob.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 29, 'Once when Jacob was cooking stew, Esau came in from the field, and he was exhausted.', 'Esau Sells His Birthright', 'ESV'),
('genesis', 'Genesis', 1, 25, 30, 'And Esau said to Jacob, "Let me eat some of that red stew, for I am exhausted!" (Therefore his name was called Edom.)', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 31, 'Jacob said, "Sell me your birthright now."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 32, 'Esau said, "I am about to die; of what use is a birthright to me?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 33, 'Jacob said, "Swear to me now." So he swore to him and sold his birthright to Jacob.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 25, 34, 'Then Jacob gave Esau bread and lentil stew, and he ate and drank and rose and went his way. Thus Esau despised his birthright.', NULL, 'ESV')
ON CONFLICT (book_id, chapter_number, verse_number, translation_code)
DO UPDATE SET verse_text = EXCLUDED.verse_text, section_heading = EXCLUDED.section_heading;

-- Chapter 26: God's Promise to Isaac
INSERT INTO bible_verses (book_id, book_name, book_order, chapter_number, verse_number, verse_text, section_heading, translation_code)
VALUES
('genesis', 'Genesis', 1, 26, 1, 'Now there was a famine in the land, besides the former famine that was in the days of Abraham. And Isaac went to Gerar to Abimelech king of the Philistines.', 'God''s Promise to Isaac', 'ESV'),
('genesis', 'Genesis', 1, 26, 2, 'And the LORD appeared to him and said, "Do not go down to Egypt; dwell in the land of which I shall tell you.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 3, 'Sojourn in this land, and I will be with you and will bless you, for to you and to your offspring I will give all these lands, and I will establish the oath that I swore to Abraham your father.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 4, 'I will multiply your offspring as the stars of heaven and will give to your offspring all these lands. And in your offspring all the nations of the earth shall be blessed,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 5, 'because Abraham obeyed my voice and kept my charge, my commandments, my statutes, and my laws."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 6, 'So Isaac settled in Gerar.', 'Isaac and Abimelech', 'ESV'),
('genesis', 'Genesis', 1, 26, 7, 'When the men of the place asked him about his wife, he said, "She is my sister," for he feared to say, "My wife," thinking, "lest the men of the place should kill me because of Rebekah," because she was attractive in appearance.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 8, 'When he had been there a long time, Abimelech king of the Philistines looked out of a window and saw Isaac laughing with Rebekah his wife.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 9, 'So Abimelech called Isaac and said, "Behold, she is your wife. How then could you say, ''She is my sister''?" Isaac said to him, "Because I thought, ''Lest I die because of her.''"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 10, 'Abimelech said, "What is this you have done to us? One of the people might easily have lain with your wife, and you would have brought guilt upon us."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 11, 'So Abimelech warned all the people, saying, "Whoever touches this man or his wife shall surely be put to death."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 12, 'And Isaac sowed in that land and reaped in the same year a hundredfold. The LORD blessed him,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 13, 'and the man became rich, and gained more and more until he became very wealthy.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 14, 'He had possessions of flocks and herds and many servants, so that the Philistines envied him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 15, '(Now the Philistines had stopped and filled with earth all the wells that his father''s servants had dug in the days of Abraham his father.)', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 16, 'And Abimelech said to Isaac, "Go away from us, for you are much mightier than we."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 17, 'So Isaac departed from there and encamped in the Valley of Gerar and settled there.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 18, 'And Isaac dug again the wells of water that had been dug in the days of Abraham his father, which the Philistines had stopped after the death of Abraham. And he gave them the names that his father had given them.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 19, 'But when Isaac''s servants dug in the valley and found there a well of spring water,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 20, 'the herdsmen of Gerar quarreled with Isaac''s herdsmen, saying, "The water is ours." So he called the name of the well Esek, because they contended with him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 21, 'Then they dug another well, and they quarreled over that also, so he called its name Sitnah.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 22, 'And he moved from there and dug another well, and they did not quarrel over it. So he called its name Rehoboth, saying, "For now the LORD has made room for us, and we shall be fruitful in the land."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 23, 'From there he went up to Beersheba.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 24, 'And the LORD appeared to him the same night and said, "I am the God of Abraham your father. Fear not, for I am with you and will bless you and multiply your offspring for my servant Abraham''s sake."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 25, 'So he built an altar there and called upon the name of the LORD and pitched his tent there. And there Isaac''s servants dug a well.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 26, 'When Abimelech went to him from Gerar with Ahuzzath his adviser and Phicol the commander of his army,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 27, 'Isaac said to them, "Why have you come to me, seeing that you hate me and have sent me away from you?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 28, 'They said, "We see plainly that the LORD has been with you. So we said, let there be a sworn pact between us, between you and us, and let us make a covenant with you,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 29, 'that you will do us no harm, just as we have not touched you and have done to you nothing but good and have sent you away in peace. You are now the blessed of the LORD."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 30, 'So he made them a feast, and they ate and drank.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 31, 'In the morning they rose early and exchanged oaths. And Isaac sent them on their way, and they departed from him in peace.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 32, 'That same day Isaac''s servants came and told him about the well that they had dug and said to him, "We have found water."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 33, 'He called it Shibah; therefore the name of the city is Beersheba to this day.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 34, 'When Esau was forty years old, he took Judith the daughter of Beeri the Hittite to be his wife, and Basemath the daughter of Elon the Hittite,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 26, 35, 'and they made life bitter for Isaac and Rebekah.', NULL, 'ESV')
ON CONFLICT (book_id, chapter_number, verse_number, translation_code)
DO UPDATE SET verse_text = EXCLUDED.verse_text, section_heading = EXCLUDED.section_heading;

-- Chapter 27: Isaac Blesses Jacob
INSERT INTO bible_verses (book_id, book_name, book_order, chapter_number, verse_number, verse_text, section_heading, translation_code)
VALUES
('genesis', 'Genesis', 1, 27, 1, 'When Isaac was old and his eyes were dim so that he could not see, he called Esau his older son and said to him, "My son"; and he answered, "Here I am."', 'Isaac Blesses Jacob', 'ESV'),
('genesis', 'Genesis', 1, 27, 2, 'He said, "Behold, I am old; I do not know the day of my death.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 3, 'Now then, take your weapons, your quiver and your bow, and go out to the field and hunt game for me,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 4, 'and prepare for me delicious food, such as I love, and bring it to me so that I may eat, that my soul may bless you before I die."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 5, 'Now Rebekah was listening when Isaac spoke to his son Esau. So when Esau went to the field to hunt for game and bring it,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 6, 'Rebekah said to her son Jacob, "I heard your father speak to your brother Esau,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 7, '''Bring me game and prepare for me delicious food, that I may eat it and bless you before the LORD before I die.''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 8, 'Now therefore, my son, obey my voice as I command you.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 9, 'Go to the flock and bring me two good young goats, so that I may prepare from them delicious food for your father, such as he loves.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 10, 'And you shall bring it to your father to eat, so that he may bless you before he dies."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 11, 'But Jacob said to Rebekah his mother, "Behold, my brother Esau is a hairy man, and I am a smooth man.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 12, 'Perhaps my father will feel me, and I shall seem to be mocking him and bring a curse upon myself and not a blessing."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 13, 'His mother said to him, "Let your curse be on me, my son; only obey my voice, and go, bring them to me."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 14, 'So he went and took them and brought them to his mother, and his mother prepared delicious food, such as his father loved.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 15, 'Then Rebekah took the best garments of Esau her older son, which were with her in the house, and put them on Jacob her younger son.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 16, 'And the skins of the young goats she put on his hands and on the smooth part of his neck.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 17, 'And she put the delicious food and the bread, which she had prepared, into the hand of her son Jacob.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 18, 'So he went in to his father and said, "My father." And he said, "Here I am. Who are you, my son?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 19, 'Jacob said to his father, "I am Esau your firstborn. I have done as you told me; now sit up and eat of my game, that your soul may bless me."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 20, 'But Isaac said to his son, "How is it that you have found it so quickly, my son?" He answered, "Because the LORD your God granted me success."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 21, 'Then Isaac said to Jacob, "Please come near, that I may feel you, my son, to know whether you are really my son Esau or not."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 22, 'So Jacob went near to Isaac his father, who felt him and said, "The voice is Jacob''s voice, but the hands are the hands of Esau."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 23, 'And he did not recognize him, because his hands were hairy like his brother Esau''s hands. So he blessed him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 24, 'He said, "Are you really my son Esau?" He answered, "I am."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 25, 'Then he said, "Bring it near to me, that I may eat of my son''s game and bless you." So he brought it near to him, and he ate; and he brought him wine, and he drank.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 26, 'Then his father Isaac said to him, "Come near and kiss me, my son."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 27, 'So he came near and kissed him. And Isaac smelled the smell of his garments and blessed him and said, "See, the smell of my son is as the smell of a field that the LORD has blessed!', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 28, 'May God give you of the dew of heaven and of the fatness of the earth and plenty of grain and wine.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 29, 'Let peoples serve you, and nations bow down to you. Be lord over your brothers, and may your mother''s sons bow down to you. Cursed be everyone who curses you, and blessed be everyone who blesses you!"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 30, 'As soon as Isaac had finished blessing Jacob, when Jacob had scarcely gone out from the presence of Isaac his father, Esau his brother came in from his hunting.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 31, 'He also prepared delicious food and brought it to his father. And he said to his father, "Let my father arise and eat of his son''s game, that you may bless me."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 32, 'His father Isaac said to him, "Who are you?" He answered, "I am your son, your firstborn, Esau."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 33, 'Then Isaac trembled very violently and said, "Who was it then that hunted game and brought it to me, and I ate it all before you came, and I have blessed him? Yes, and he shall be blessed."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 34, 'As soon as Esau heard the words of his father, he cried out with an exceedingly great and bitter cry and said to his father, "Bless me, even me also, O my father!"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 35, 'But he said, "Your brother came deceitfully, and he has taken away your blessing."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 36, 'Esau said, "Is he not rightly named Jacob? For he has cheated me these two times. He took away my birthright, and behold, now he has taken away my blessing." Then he said, "Have you not reserved a blessing for me?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 37, 'Isaac answered and said to Esau, "Behold, I have made him lord over you, and all his brothers I have given to him for servants, and with grain and wine I have sustained him. What then can I do for you, my son?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 38, 'Esau said to his father, "Have you but one blessing, my father? Bless me, even me also, O my father." And Esau lifted up his voice and wept.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 39, 'Then Isaac his father answered and said to him: "Behold, away from the fatness of the earth shall your dwelling be, and away from the dew of heaven on high.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 40, 'By your sword you shall live, and you shall serve your brother; but when you grow restless you shall break his yoke from your neck."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 41, 'Now Esau hated Jacob because of the blessing with which his father had blessed him, and Esau said to himself, "The days of mourning for my father are approaching; then I will kill my brother Jacob."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 42, 'But the words of Esau her older son were told to Rebekah. So she sent and called Jacob her younger son and said to him, "Behold, your brother Esau comforts himself about you by planning to kill you.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 43, 'Now therefore, my son, obey my voice. Arise, flee to Laban my brother in Haran', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 44, 'and stay with him a while, until your brother''s fury turns away—', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 45, 'until your brother''s anger turns away from you, and he forgets what you have done to him. Then I will send and bring you from there. Why should I be bereft of you both in one day?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 27, 46, 'Then Rebekah said to Isaac, "I loathe my life because of the Hittite women. If Jacob marries one of the Hittite women like these, one of the women of the land, what good will my life be to me?"', NULL, 'ESV')
ON CONFLICT (book_id, chapter_number, verse_number, translation_code)
DO UPDATE SET verse_text = EXCLUDED.verse_text, section_heading = EXCLUDED.section_heading;

-- Chapter 28: Jacob Sent to Laban
INSERT INTO bible_verses (book_id, book_name, book_order, chapter_number, verse_number, verse_text, section_heading, translation_code)
VALUES
('genesis', 'Genesis', 1, 28, 1, 'Then Isaac called Jacob and blessed him and directed him, "You must not take a wife from the Canaanite women.', 'Jacob Sent to Laban', 'ESV'),
('genesis', 'Genesis', 1, 28, 2, 'Arise, go to Paddan-aram to the house of Bethuel your mother''s father, and take as your wife from there one of the daughters of Laban your mother''s brother.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 28, 3, 'God Almighty bless you and make you fruitful and multiply you, that you may become a company of peoples.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 28, 4, 'May he give the blessing of Abraham to you and to your offspring with you, that you may take possession of the land of your sojournings that God gave to Abraham!"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 28, 5, 'Thus Isaac sent Jacob away. And he went to Paddan-aram, to Laban, the son of Bethuel the Aramean, the brother of Rebekah, Jacob''s and Esau''s mother.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 28, 6, 'Now Esau saw that Isaac had blessed Jacob and sent him away to Paddan-aram to take a wife from there, and that as he blessed him he directed him, "You must not take a wife from the Canaanite women,"', 'Esau Marries an Ishmaelite', 'ESV'),
('genesis', 'Genesis', 1, 28, 7, 'and that Jacob had obeyed his father and his mother and gone to Paddan-aram.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 28, 8, 'So when Esau saw that the Canaanite women did not please Isaac his father,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 28, 9, 'Esau went to Ishmael and took as his wife, besides the wives he had, Mahalath the daughter of Ishmael, Abraham''s son, the sister of Nebaioth.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 28, 10, 'Jacob left Beersheba and went toward Haran.', 'Jacob''s Dream', 'ESV'),
('genesis', 'Genesis', 1, 28, 11, 'And he came to a certain place and stayed there that night, because the sun had set. Taking one of the stones of the place, he put it under his head and lay down in that place to sleep.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 28, 12, 'And he dreamed, and behold, there was a ladder set up on the earth, and the top of it reached to heaven. And behold, the angels of God were ascending and descending on it!', NULL, 'ESV'),
('genesis', 'Genesis', 1, 28, 13, 'And behold, the LORD stood above it and said, "I am the LORD, the God of Abraham your father and the God of Isaac. The land on which you lie I will give to you and to your offspring.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 28, 14, 'Your offspring shall be like the dust of the earth, and you shall spread abroad to the west and to the east and to the north and to the south, and in you and your offspring shall all the families of the earth be blessed.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 28, 15, 'Behold, I am with you and will keep you wherever you go, and will bring you back to this land. For I will not leave you until I have done what I have promised you."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 28, 16, 'Then Jacob awoke from his sleep and said, "Surely the LORD is in this place, and I did not know it."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 28, 17, 'And he was afraid and said, "How awesome is this place! This is none other than the house of God, and this is the gate of heaven."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 28, 18, 'So early in the morning Jacob took the stone that he had put under his head and set it up for a pillar and poured oil on the top of it.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 28, 19, 'He called the name of that place Bethel, but the name of the city was Luz at the first.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 28, 20, 'Then Jacob made a vow, saying, "If God will be with me and will keep me in this way that I go, and will give me bread to eat and clothing to wear,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 28, 21, 'so that I come again to my father''s house in peace, then the LORD shall be my God,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 28, 22, 'and this stone, which I have set up for a pillar, shall be God''s house. And of all that you give me I will give a full tenth to you."', NULL, 'ESV')
ON CONFLICT (book_id, chapter_number, verse_number, translation_code)
DO UPDATE SET verse_text = EXCLUDED.verse_text, section_heading = EXCLUDED.section_heading;

-- Chapter 29: Jacob Marries Leah and Rachel
INSERT INTO bible_verses (book_id, book_name, book_order, chapter_number, verse_number, verse_text, section_heading, translation_code)
VALUES
('genesis', 'Genesis', 1, 29, 1, 'Then Jacob went on his journey and came to the land of the people of the east.', 'Jacob Marries Leah and Rachel', 'ESV'),
('genesis', 'Genesis', 1, 29, 2, 'As he looked, he saw a well in the field, and behold, three flocks of sheep lying beside it, for out of that well the flocks were watered. The stone on the well''s mouth was large,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 3, 'and when all the flocks were gathered there, the shepherds would roll the stone from the mouth of the well and water the sheep, and put the stone back in its place over the mouth of the well.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 4, 'Jacob said to them, "My brothers, where do you come from?" They said, "We are from Haran."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 5, 'He said to them, "Do you know Laban the son of Nahor?" They said, "We know him."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 6, 'He said to them, "Is it well with him?" They said, "It is well; and see, Rachel his daughter is coming with the sheep!"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 7, 'He said, "Behold, it is still high day; it is not time for the livestock to be gathered together. Water the sheep and go, pasture them."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 8, 'But they said, "We cannot until all the flocks are gathered together and the stone is rolled from the mouth of the well; then we water the sheep."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 9, 'While he was still speaking with them, Rachel came with her father''s sheep, for she was a shepherdess.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 10, 'Now as soon as Jacob saw Rachel the daughter of Laban his mother''s brother, and the sheep of Laban his mother''s brother, Jacob came near and rolled the stone from the well''s mouth and watered the flock of Laban his mother''s brother.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 11, 'Then Jacob kissed Rachel and wept aloud.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 12, 'And Jacob told Rachel that he was her father''s kinsman, and that he was Rebekah''s son, and she ran and told her father.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 13, 'As soon as Laban heard the news about Jacob, his sister''s son, he ran to meet him and embraced him and kissed him and brought him to his house. Jacob told Laban all these things,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 14, 'and Laban said to him, "Surely you are my bone and my flesh!" And he stayed with him a month.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 15, 'Then Laban said to Jacob, "Because you are my kinsman, should you therefore serve me for nothing? Tell me, what shall your wages be?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 16, 'Now Laban had two daughters. The name of the older was Leah, and the name of the younger was Rachel.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 17, 'Leah''s eyes were weak, but Rachel was beautiful in form and appearance.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 18, 'Jacob loved Rachel. And he said, "I will serve you seven years for your younger daughter Rachel."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 19, 'Laban said, "It is better that I give her to you than that I should give her to any other man; stay with me."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 20, 'So Jacob served seven years for Rachel, and they seemed to him but a few days because of the love he had for her.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 21, 'Then Jacob said to Laban, "Give me my wife that I may go in to her, for my time is completed."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 22, 'So Laban gathered together all the people of the place and made a feast.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 23, 'But in the evening he took his daughter Leah and brought her to Jacob, and he went in to her.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 24, '(Laban gave his female servant Zilpah to his daughter Leah to be her servant.)', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 25, 'And in the morning, behold, it was Leah! And Jacob said to Laban, "What is this you have done to me? Did I not serve with you for Rachel? Why then have you deceived me?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 26, 'Laban said, "It is not so done in our country, to give the younger before the firstborn.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 27, 'Complete the week of this one, and we will give you the other also in return for serving me another seven years."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 28, 'Jacob did so, and completed her week. Then Laban gave him his daughter Rachel to be his wife.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 29, '(Laban gave his female servant Bilhah to his daughter Rachel to be her servant.)', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 30, 'So Jacob went in to Rachel also, and he loved Rachel more than Leah, and served Laban for another seven years.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 31, 'When the LORD saw that Leah was hated, he opened her womb, but Rachel was barren.', 'Jacob''s Children', 'ESV'),
('genesis', 'Genesis', 1, 29, 32, 'And Leah conceived and bore a son, and she called his name Reuben, for she said, "Because the LORD has looked upon my affliction; for now my husband will love me."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 33, 'She conceived again and bore a son, and said, "Because the LORD has heard that I am hated, he has given me this son also." And she called his name Simeon.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 34, 'Again she conceived and bore a son, and said, "Now this time my husband will be attached to me, because I have borne him three sons." Therefore his name was called Levi.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 29, 35, 'And she conceived again and bore a son, and said, "This time I will praise the LORD." Therefore she called his name Judah. Then she ceased bearing.', NULL, 'ESV')
ON CONFLICT (book_id, chapter_number, verse_number, translation_code)
DO UPDATE SET verse_text = EXCLUDED.verse_text, section_heading = EXCLUDED.section_heading;

-- Chapter 30: Jacob's Children (continued)
INSERT INTO bible_verses (book_id, book_name, book_order, chapter_number, verse_number, verse_text, section_heading, translation_code)
VALUES
('genesis', 'Genesis', 1, 30, 1, 'When Rachel saw that she bore Jacob no children, she envied her sister. She said to Jacob, "Give me children, or I shall die!"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 2, 'Jacob''s anger was kindled against Rachel, and he said, "Am I in the place of God, who has withheld from you the fruit of the womb?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 3, 'Then she said, "Here is my servant Bilhah; go in to her, so that she may give birth on my behalf, that even I may have children through her."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 4, 'So she gave him her servant Bilhah as a wife, and Jacob went in to her.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 5, 'And Bilhah conceived and bore Jacob a son.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 6, 'Then Rachel said, "God has judged me, and has also heard my voice and given me a son." Therefore she called his name Dan.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 7, 'Rachel''s servant Bilhah conceived again and bore Jacob a second son.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 8, 'Then Rachel said, "With mighty wrestlings I have wrestled with my sister and have prevailed." So she called his name Naphtali.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 9, 'When Leah saw that she had ceased bearing children, she took her servant Zilpah and gave her to Jacob as a wife.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 10, 'Then Leah''s servant Zilpah bore Jacob a son.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 11, 'And Leah said, "Good fortune has come!" so she called his name Gad.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 12, 'Leah''s servant Zilpah bore Jacob a second son.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 13, 'And Leah said, "Happy am I! For women have called me happy." So she called his name Asher.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 14, 'In the days of wheat harvest Reuben went and found mandrakes in the field and brought them to his mother Leah. Then Rachel said to Leah, "Please give me some of your son''s mandrakes."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 15, 'But she said to her, "Is it a small matter that you have taken away my husband? Would you take away my son''s mandrakes also?" Rachel said, "Then he may lie with you tonight in exchange for your son''s mandrakes."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 16, 'When Jacob came from the field in the evening, Leah went out to meet him and said, "You must come in to me, for I have hired you with my son''s mandrakes." So he lay with her that night.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 17, 'And God listened to Leah, and she conceived and bore Jacob a fifth son.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 18, 'Leah said, "God has given me my wages because I gave my servant to my husband." So she called his name Issachar.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 19, 'And Leah conceived again, and she bore Jacob a sixth son.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 20, 'Then Leah said, "God has endowed me with a good endowment; now my husband will honor me, because I have borne him six sons." So she called his name Zebulun.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 21, 'Afterward she bore a daughter and called her name Dinah.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 22, 'Then God remembered Rachel, and God listened to her and opened her womb.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 23, 'She conceived and bore a son and said, "God has taken away my reproach."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 24, 'And she called his name Joseph, saying, "May the LORD add to me another son!"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 25, 'As soon as Rachel had borne Joseph, Jacob said to Laban, "Send me away, that I may go to my own home and country.', 'Jacob''s Prosperity', 'ESV'),
('genesis', 'Genesis', 1, 30, 26, 'Give me my wives and my children for whom I have served you, that I may go, for you know the service that I have given you."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 27, 'But Laban said to him, "If I have found favor in your sight, I have learned by divination that the LORD has blessed me because of you.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 28, 'Name your wages, and I will give it."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 29, 'Jacob said to him, "You yourself know how I have served you, and how your livestock has fared with me.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 30, 'For you had little before I came, and it has increased abundantly, and the LORD has blessed you wherever I turned. But now when shall I provide for my own household also?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 31, 'He said, "What shall I give you?" Jacob said, "You shall not give me anything. If you will do this for me, I will again pasture your flock and keep it:', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 32, 'let me pass through all your flock today, removing from it every speckled and spotted sheep and every black lamb, and the spotted and speckled among the goats, and they shall be my wages.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 33, 'So my honesty will answer for me later, when you come to look into my wages with you. Every one that is not speckled and spotted among the goats and black among the lambs, if found with me, shall be counted stolen."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 34, 'Laban said, "Good! Let it be as you have said."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 35, 'But that day Laban removed the male goats that were striped and spotted, and all the female goats that were speckled and spotted, every one that had white on it, and every lamb that was black, and put them in the charge of his sons.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 36, 'And he set a distance of three days'' journey between himself and Jacob, and Jacob pastured the rest of Laban''s flock.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 37, 'Then Jacob took fresh sticks of poplar and almond and plane trees, and peeled white streaks in them, exposing the white of the sticks.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 38, 'He set the sticks that he had peeled in front of the flocks in the troughs, that is, the watering places, where the flocks came to drink. And since they bred when they came to drink,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 39, 'the flocks bred in front of the sticks and so the flocks brought forth striped, speckled, and spotted.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 40, 'And Jacob separated the lambs and set the faces of the flocks toward the striped and all the black in the flock of Laban. He put his own droves apart and did not put them with Laban''s flock.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 41, 'Whenever the stronger of the flock were breeding, Jacob would lay the sticks in the troughs before the eyes of the flock, that they might breed among the sticks,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 42, 'but for the feebler of the flock he would not lay them there. So the feebler would be Laban''s, and the stronger Jacob''s.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 30, 43, 'Thus the man increased greatly and had large flocks, female servants and male servants, and camels and donkeys.', NULL, 'ESV')
ON CONFLICT (book_id, chapter_number, verse_number, translation_code)
DO UPDATE SET verse_text = EXCLUDED.verse_text, section_heading = EXCLUDED.section_heading;

-- Chapter 31: Jacob Flees from Laban
INSERT INTO bible_verses (book_id, book_name, book_order, chapter_number, verse_number, verse_text, section_heading, translation_code)
VALUES
('genesis', 'Genesis', 1, 31, 1, 'Now Jacob heard that the sons of Laban were saying, "Jacob has taken all that was our father''s, and from what was our father''s he has gained all this wealth."', 'Jacob Flees from Laban', 'ESV'),
('genesis', 'Genesis', 1, 31, 2, 'And Jacob saw that Laban did not regard him with favor as before.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 3, 'Then the LORD said to Jacob, "Return to the land of your fathers and to your kindred, and I will be with you."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 4, 'So Jacob sent and called Rachel and Leah into the field where his flock was', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 5, 'and said to them, "I see that your father does not regard me with favor as he did before. But the God of my father has been with me.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 6, 'You know that I have served your father with all my strength,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 7, 'yet your father has cheated me and changed my wages ten times. But God did not permit him to harm me.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 8, 'If he said, ''The spotted shall be your wages,'' then all the flock bore spotted; and if he said, ''The striped shall be your wages,'' then all the flock bore striped.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 9, 'Thus God has taken away the livestock of your father and given them to me.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 10, 'In the breeding season of the flock I lifted up my eyes and saw in a dream that the goats that mated with the flock were striped, spotted, and mottled.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 11, 'Then the angel of God said to me in the dream, ''Jacob,'' and I said, ''Here I am!''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 12, 'And he said, ''Lift up your eyes and see, all the goats that mate with the flock are striped, spotted, and mottled, for I have seen all that Laban is doing to you.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 13, 'I am the God of Bethel, where you anointed a pillar and made a vow to me. Now arise, go out from this land and return to the land of your kindred.''"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 14, 'Then Rachel and Leah answered and said to him, "Is there any portion or inheritance left to us in our father''s house?', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 15, 'Are we not regarded by him as foreigners? For he has sold us, and he has indeed devoured our money.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 16, 'All the wealth that God has taken away from our father belongs to us and to our children. Now then, whatever God has said to you, do."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 17, 'So Jacob arose and set his sons and his wives on camels.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 18, 'He drove away all his livestock, all his property that he had gained, the livestock in his possession that he had acquired in Paddan-aram, to go to the land of Canaan to his father Isaac.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 19, 'Laban had gone to shear his sheep, and Rachel stole her father''s household gods.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 20, 'And Jacob tricked Laban the Aramean, by not telling him that he intended to flee.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 21, 'He fled with all that he had and arose and crossed the Euphrates, and set his face toward the hill country of Gilead.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 22, 'When it was told Laban on the third day that Jacob had fled,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 23, 'he took his kinsmen with him and pursued him for seven days and followed close after him into the hill country of Gilead.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 24, 'But God came to Laban the Aramean in a dream by night and said to him, "Be careful not to say anything to Jacob, either good or bad."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 25, 'And Laban overtook Jacob. Now Jacob had pitched his tent in the hill country, and Laban with his kinsmen pitched tents in the hill country of Gilead.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 26, 'And Laban said to Jacob, "What have you done, that you have tricked me and driven away my daughters like captives of the sword?', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 27, 'Why did you flee secretly and trick me, and did not tell me, so that I might have sent you away with mirth and songs, with tambourine and lyre?', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 28, 'And why did you not permit me to kiss my sons and my daughters farewell? Now you have done foolishly.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 29, 'It is in my power to do you harm. But the God of your father spoke to me last night, saying, ''Be careful not to say anything to Jacob, either good or bad.''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 30, 'And now you have gone away because you longed greatly for your father''s house, but why did you steal my gods?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 31, 'Jacob answered and said to Laban, "Because I was afraid, for I thought that you would take your daughters from me by force.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 32, 'Anyone with whom you find your gods shall not live. In the presence of our kinsmen point out what I have that is yours, and take it." Now Jacob did not know that Rachel had stolen them.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 33, 'So Laban went into Jacob''s tent and into Leah''s tent and into the tent of the two female servants, but he did not find them. And he went out of Leah''s tent and entered Rachel''s.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 34, 'Now Rachel had taken the household gods and put them in the camel''s saddle and sat on them. Laban felt all about the tent, but did not find them.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 35, 'And she said to her father, "Let not my lord be angry that I cannot rise before you, for the way of women is upon me." So he searched but did not find the household gods.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 36, 'Then Jacob became angry and berated Laban. Jacob said to Laban, "What is my offense? What is my sin, that you have hotly pursued me?', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 37, 'For you have felt through all my goods; what have you found of all your household goods? Set it here before my kinsmen and your kinsmen, that they may decide between us two.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 38, 'These twenty years I have been with you. Your ewes and your female goats have not miscarried, and I have not eaten the rams of your flocks.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 39, 'What was torn by wild beasts I did not bring to you. I bore the loss of it myself. From my hand you required it, whether stolen by day or stolen by night.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 40, 'There I was: by day the heat consumed me, and the cold by night, and my sleep fled from my eyes.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 41, 'These twenty years I have been in your house. I served you fourteen years for your two daughters, and six years for your flock, and you have changed my wages ten times.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 42, 'If the God of my father, the God of Abraham and the Fear of Isaac, had not been on my side, surely now you would have sent me away empty-handed. God saw my affliction and the labor of my hands and rebuked you last night."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 43, 'Then Laban answered and said to Jacob, "The daughters are my daughters, the children are my children, the flocks are my flocks, and all that you see is mine. But what can I do this day for these my daughters or for their children whom they have borne?', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 44, 'Come now, let us make a covenant, you and I. And let it be a witness between you and me."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 45, 'So Jacob took a stone and set it up as a pillar.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 46, 'And Jacob said to his kinsmen, "Gather stones." And they took stones and made a heap, and they ate there by the heap.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 47, 'Laban called it Jegar-sahadutha, but Jacob called it Galeed.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 48, 'Laban said, "This heap is a witness between you and me today." Therefore he named it Galeed,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 49, 'and Mizpah, for he said, "The LORD watch between you and me, when we are out of one another''s sight.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 50, 'If you oppress my daughters, or if you take wives besides my daughters, although no one is with us, see, God is witness between you and me."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 51, 'Then Laban said to Jacob, "See this heap and the pillar, which I have set between you and me.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 52, 'This heap is a witness, and the pillar is a witness, that I will not pass over this heap to you, and you will not pass over this heap and this pillar to me, to do harm.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 53, 'The God of Abraham and the God of Nahor, the God of their father, judge between us." So Jacob swore by the Fear of his father Isaac,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 54, 'and Jacob offered a sacrifice in the hill country and called his kinsmen to eat bread. They ate bread and spent the night in the hill country.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 31, 55, 'Early in the morning Laban arose and kissed his grandchildren and his daughters and blessed them. Then Laban departed and returned home.', NULL, 'ESV')
ON CONFLICT (book_id, chapter_number, verse_number, translation_code)
DO UPDATE SET verse_text = EXCLUDED.verse_text, section_heading = EXCLUDED.section_heading;
