-- Migration: Insert Genesis chapters 32-37 (ESV)
-- Book: Genesis (book_id: genesis, book_order: 1)

-- Chapter 32: Jacob Fears Esau
INSERT INTO bible_verses (book_id, book_name, book_order, chapter_number, verse_number, verse_text, section_heading, translation_code)
VALUES
('genesis', 'Genesis', 1, 32, 1, 'Jacob went on his way, and the angels of God met him.', 'Jacob Fears Esau', 'ESV'),
('genesis', 'Genesis', 1, 32, 2, 'And when Jacob saw them he said, "This is God''s camp!" So he called the name of that place Mahanaim.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 3, 'And Jacob sent messengers before him to Esau his brother in the land of Seir, the country of Edom,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 4, 'instructing them, "Thus you shall say to my lord Esau: Thus says your servant Jacob, ''I have sojourned with Laban and stayed until now.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 5, 'I have oxen, donkeys, flocks, male servants, and female servants. I have sent to tell my lord, in order that I may find favor in your sight.''"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 6, 'And the messengers returned to Jacob, saying, "We came to your brother Esau, and he is coming to meet you, and there are four hundred men with him."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 7, 'Then Jacob was greatly afraid and distressed. He divided the people who were with him, and the flocks and herds and camels, into two camps,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 8, 'thinking, "If Esau comes to the one camp and attacks it, then the camp that is left will escape."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 9, 'And Jacob said, "O God of my father Abraham and God of my father Isaac, O LORD who said to me, ''Return to your country and to your kindred, that I may do you good,''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 10, 'I am not worthy of the least of all the deeds of steadfast love and all the faithfulness that you have shown to your servant, for with only my staff I crossed this Jordan, and now I have become two camps.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 11, 'Please deliver me from the hand of my brother, from the hand of Esau, for I fear him, that he may come and attack me, the mothers with the children.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 12, 'But you said, ''I will surely do you good, and make your offspring as the sand of the sea, which cannot be numbered for multitude.''"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 13, 'So he stayed there that night, and from what he had with him he took a present for his brother Esau,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 14, 'two hundred female goats and twenty male goats, two hundred ewes and twenty rams,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 15, 'thirty milking camels and their calves, forty cows and ten bulls, twenty female donkeys and ten male donkeys.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 16, 'These he handed over to his servants, every drove by itself, and said to his servants, "Pass on ahead of me and put a space between drove and drove."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 17, 'He instructed the first, "When Esau my brother meets you and asks you, ''To whom do you belong? Where are you going? And whose are these ahead of you?''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 18, 'then you shall say, ''They belong to your servant Jacob. They are a present sent to my lord Esau. And moreover, he is behind us.''"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 19, 'He likewise instructed the second and the third and all who followed the droves, "You shall say the same thing to Esau when you find him,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 20, 'and you shall say, ''Moreover, your servant Jacob is behind us.''" For he thought, "I may appease him with the present that goes ahead of me, and afterward I shall see his face. Perhaps he will accept me."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 21, 'So the present passed on ahead of him, and he himself stayed that night in the camp.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 22, 'The same night he arose and took his two wives, his two female servants, and his eleven children, and crossed the ford of the Jabbok.', 'Jacob Wrestles with God', 'ESV'),
('genesis', 'Genesis', 1, 32, 23, 'He took them and sent them across the stream, and everything else that he had.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 24, 'And Jacob was left alone. And a man wrestled with him until the breaking of the day.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 25, 'When the man saw that he did not prevail against Jacob, he touched his hip socket, and Jacob''s hip was put out of joint as he wrestled with him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 26, 'Then he said, "Let me go, for the day has broken." But Jacob said, "I will not let you go unless you bless me."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 27, 'And he said to him, "What is your name?" And he said, "Jacob."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 28, 'Then he said, "Your name shall no longer be called Jacob, but Israel, for you have striven with God and with men, and have prevailed."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 29, 'Then Jacob asked him, "Please tell me your name." But he said, "Why is it that you ask my name?" And there he blessed him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 30, 'So Jacob called the name of the place Peniel, saying, "For I have seen God face to face, and yet my life has been delivered."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 31, 'The sun rose upon him as he passed Penuel, limping because of his hip.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 32, 32, 'Therefore to this day the people of Israel do not eat the sinew of the thigh that is on the hip socket, because he touched the socket of Jacob''s hip on the sinew of the thigh.', NULL, 'ESV')
ON CONFLICT (book_id, chapter_number, verse_number, translation_code)
DO UPDATE SET verse_text = EXCLUDED.verse_text, section_heading = EXCLUDED.section_heading;

-- Chapter 33: Jacob Meets Esau
INSERT INTO bible_verses (book_id, book_name, book_order, chapter_number, verse_number, verse_text, section_heading, translation_code)
VALUES
('genesis', 'Genesis', 1, 33, 1, 'And Jacob lifted up his eyes and looked, and behold, Esau was coming, and four hundred men with him. So he divided the children among Leah and Rachel and the two female servants.', 'Jacob Meets Esau', 'ESV'),
('genesis', 'Genesis', 1, 33, 2, 'And he put the servants with their children in front, then Leah with her children, and Rachel and Joseph last of all.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 33, 3, 'He himself went on before them, bowing himself to the ground seven times, until he came near to his brother.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 33, 4, 'But Esau ran to meet him and embraced him and fell on his neck and kissed him, and they wept.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 33, 5, 'And when Esau lifted up his eyes and saw the women and children, he said, "Who are these with you?" Jacob said, "The children whom God has graciously given your servant."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 33, 6, 'Then the servants drew near, they and their children, and bowed down.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 33, 7, 'Leah likewise and her children drew near and bowed down. And last Joseph and Rachel drew near, and they bowed down.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 33, 8, 'Esau said, "What do you mean by all this company that I met?" Jacob answered, "To find favor in the sight of my lord."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 33, 9, 'But Esau said, "I have enough, my brother; keep what you have for yourself."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 33, 10, 'Jacob said, "No, please, if I have found favor in your sight, then accept my present from my hand. For I have seen your face, which is like seeing the face of God, and you have accepted me.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 33, 11, 'Please accept my blessing that is brought to you, because God has dealt graciously with me, and because I have enough." Thus he urged him, and he took it.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 33, 12, 'Then Esau said, "Let us journey on our way, and I will go ahead of you."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 33, 13, 'But Jacob said to him, "My lord knows that the children are frail, and that the nursing flocks and herds are a care to me. If they are driven hard for one day, all the flocks will die.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 33, 14, 'Let my lord pass on ahead of his servant, and I will lead on slowly, at the pace of the livestock that are ahead of me and at the pace of the children, until I come to my lord in Seir."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 33, 15, 'So Esau said, "Let me leave with you some of the people who are with me." But he said, "What need is there? Let me find favor in the sight of my lord."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 33, 16, 'So Esau returned that day on his way to Seir.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 33, 17, 'But Jacob journeyed to Succoth, and built himself a house and made booths for his livestock. Therefore the name of the place is called Succoth.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 33, 18, 'And Jacob came safely to the city of Shechem, which is in the land of Canaan, on his way from Paddan-aram, and he camped before the city.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 33, 19, 'And from the sons of Hamor, Shechem''s father, he bought for a hundred pieces of money the piece of land on which he had pitched his tent.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 33, 20, 'There he erected an altar and called it El-Elohe-Israel.', NULL, 'ESV')
ON CONFLICT (book_id, chapter_number, verse_number, translation_code)
DO UPDATE SET verse_text = EXCLUDED.verse_text, section_heading = EXCLUDED.section_heading;

-- Chapter 34: The Defiling of Dinah
INSERT INTO bible_verses (book_id, book_name, book_order, chapter_number, verse_number, verse_text, section_heading, translation_code)
VALUES
('genesis', 'Genesis', 1, 34, 1, 'Now Dinah the daughter of Leah, whom she had borne to Jacob, went out to see the women of the land.', 'The Defiling of Dinah', 'ESV'),
('genesis', 'Genesis', 1, 34, 2, 'And when Shechem the son of Hamor the Hivite, the prince of the land, saw her, he seized her and lay with her and humiliated her.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 3, 'And his soul was drawn to Dinah the daughter of Jacob. He loved the young woman and spoke tenderly to her.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 4, 'So Shechem spoke to his father Hamor, saying, "Get me this girl for my wife."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 5, 'Now Jacob heard that he had defiled his daughter Dinah. But his sons were with his livestock in the field, so Jacob held his peace until they came.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 6, 'And Hamor the father of Shechem went out to Jacob to speak with him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 7, 'The sons of Jacob had come in from the field as soon as they heard of it, and the men were indignant and very angry, because he had done an outrageous thing in Israel by lying with Jacob''s daughter, for such a thing must not be done.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 8, 'But Hamor spoke with them, saying, "The soul of my son Shechem longs for your daughter. Please give her to him to be his wife.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 9, 'Make marriages with us. Give your daughters to us, and take our daughters for yourselves.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 10, 'You shall dwell with us, and the land shall be open to you. Dwell and trade in it, and get property in it."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 11, 'Shechem also said to her father and to her brothers, "Let me find favor in your eyes, and whatever you say to me I will give.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 12, 'Ask me for as great a bride price and gift as you will, and I will give whatever you say to me. Only give me the young woman to be my wife."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 13, 'The sons of Jacob answered Shechem and his father Hamor deceitfully, because he had defiled their sister Dinah.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 14, 'They said to them, "We cannot do this thing, to give our sister to one who is uncircumcised, for that would be a disgrace to us.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 15, 'Only on this condition will we agree with you—that you will become as we are by every male among you being circumcised.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 16, 'Then we will give our daughters to you, and we will take your daughters to ourselves, and we will dwell with you and become one people.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 17, 'But if you will not listen to us and be circumcised, then we will take our daughter, and we will be gone."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 18, 'Their words pleased Hamor and Hamor''s son Shechem.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 19, 'And the young man did not delay to do the thing, because he delighted in Jacob''s daughter. Now he was the most honored of all his father''s house.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 20, 'So Hamor and his son Shechem came to the gate of their city and spoke to the men of their city, saying,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 21, '"These men are at peace with us; let them dwell in the land and trade in it, for behold, the land is large enough for them. Let us take their daughters as wives, and let us give them our daughters.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 22, 'Only on this condition will the men agree to dwell with us to become one people—when every male among us is circumcised as they are circumcised.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 23, 'Will not their livestock, their property and all their beasts be ours? Only let us agree with them, and they will dwell with us."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 24, 'And all who went out of the gate of his city listened to Hamor and his son Shechem, and every male was circumcised, all who went out of the gate of his city.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 25, 'On the third day, when they were sore, two of the sons of Jacob, Simeon and Levi, Dinah''s brothers, took their swords and came against the city while it felt secure and killed all the males.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 26, 'They killed Hamor and his son Shechem with the sword and took Dinah out of Shechem''s house and went away.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 27, 'The sons of Jacob came upon the slain and plundered the city, because they had defiled their sister.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 28, 'They took their flocks and their herds, their donkeys, and whatever was in the city and in the field.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 29, 'All their wealth, all their little ones and their wives, all that was in the houses, they captured and plundered.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 30, 'Then Jacob said to Simeon and Levi, "You have brought trouble on me by making me stink to the inhabitants of the land, the Canaanites and the Perizzites. My numbers are few, and if they gather themselves against me and attack me, I shall be destroyed, both I and my household."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 34, 31, 'But they said, "Should he treat our sister like a prostitute?"', NULL, 'ESV')
ON CONFLICT (book_id, chapter_number, verse_number, translation_code)
DO UPDATE SET verse_text = EXCLUDED.verse_text, section_heading = EXCLUDED.section_heading;

-- Chapter 35: God Blesses and Renames Jacob
INSERT INTO bible_verses (book_id, book_name, book_order, chapter_number, verse_number, verse_text, section_heading, translation_code)
VALUES
('genesis', 'Genesis', 1, 35, 1, 'God said to Jacob, "Arise, go up to Bethel and dwell there. Make an altar there to the God who appeared to you when you fled from your brother Esau."', 'God Blesses and Renames Jacob', 'ESV'),
('genesis', 'Genesis', 1, 35, 2, 'So Jacob said to his household and to all who were with him, "Put away the foreign gods that are among you and purify yourselves and change your garments.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 3, 'Then let us arise and go up to Bethel, so that I may make there an altar to the God who answers me in the day of my distress and has been with me wherever I have gone."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 4, 'So they gave to Jacob all the foreign gods that they had, and the rings that were in their ears. Jacob hid them under the terebinth tree that was near Shechem.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 5, 'And as they journeyed, a terror from God fell upon the cities that were around them, so that they did not pursue the sons of Jacob.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 6, 'And Jacob came to Luz (that is, Bethel), which is in the land of Canaan, he and all the people who were with him,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 7, 'and there he built an altar and called the place El-bethel, because there God had revealed himself to him when he fled from his brother.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 8, 'And Deborah, Rebekah''s nurse, died, and she was buried under an oak below Bethel. So he called its name Allon-bacuth.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 9, 'God appeared to Jacob again, when he came from Paddan-aram, and blessed him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 10, 'And God said to him, "Your name is Jacob; no longer shall your name be called Jacob, but Israel shall be your name." So he called his name Israel.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 11, 'And God said to him, "I am God Almighty: be fruitful and multiply. A nation and a company of nations shall come from you, and kings shall come from your own body.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 12, 'The land that I gave to Abraham and Isaac I will give to you, and I will give the land to your offspring after you."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 13, 'Then God went up from him in the place where he had spoken with him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 14, 'And Jacob set up a pillar in the place where he had spoken with him, a pillar of stone. He poured out a drink offering on it and poured oil on it.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 15, 'So Jacob called the name of the place where God had spoken with him Bethel.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 16, 'Then they journeyed from Bethel. When they were still some distance from Ephrath, Rachel went into labor, and she had hard labor.', 'The Deaths of Rachel and Isaac', 'ESV'),
('genesis', 'Genesis', 1, 35, 17, 'And when her labor was at its hardest, the midwife said to her, "Do not fear, for you have another son."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 18, 'And as her soul was departing (for she was dying), she called his name Ben-oni; but his father called him Benjamin.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 19, 'So Rachel died, and she was buried on the way to Ephrath (that is, Bethlehem),', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 20, 'and Jacob set up a pillar over her tomb. It is the pillar of Rachel''s tomb, which is there to this day.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 21, 'Israel journeyed on and pitched his tent beyond the tower of Eder.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 22, 'While Israel lived in that land, Reuben went and lay with Bilhah his father''s concubine. And Israel heard of it apply. Now the sons of Jacob were twelve.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 23, 'The sons of Leah: Reuben (Jacob''s firstborn), Simeon, Levi, Judah, Issachar, and Zebulun.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 24, 'The sons of Rachel: Joseph and Benjamin.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 25, 'The sons of Bilhah, Rachel''s servant: Dan and Naphtali.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 26, 'The sons of Zilpah, Leah''s servant: Gad and Asher. These were the sons of Jacob who were born to him in Paddan-aram.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 27, 'And Jacob came to his father Isaac at Mamre, or Kiriath-arba (that is, Hebron), where Abraham and Isaac had sojourned.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 28, 'Now the days of Isaac were 180 years.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 35, 29, 'And Isaac breathed his last, and he died and was gathered to his people, old and full of days. And his sons Esau and Jacob buried him.', NULL, 'ESV')
ON CONFLICT (book_id, chapter_number, verse_number, translation_code)
DO UPDATE SET verse_text = EXCLUDED.verse_text, section_heading = EXCLUDED.section_heading;

-- Chapter 36: Esau's Descendants
INSERT INTO bible_verses (book_id, book_name, book_order, chapter_number, verse_number, verse_text, section_heading, translation_code)
VALUES
('genesis', 'Genesis', 1, 36, 1, 'These are the generations of Esau (that is, Edom).', 'Esau''s Descendants', 'ESV'),
('genesis', 'Genesis', 1, 36, 2, 'Esau took his wives from the Canaanites: Adah the daughter of Elon the Hittite, Oholibamah the daughter of Anah the daughter of Zibeon the Hivite,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 3, 'and Basemath, Ishmael''s daughter, the sister of Nebaioth.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 4, 'And Adah bore to Esau, Eliphaz; Basemath bore Reuel;', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 5, 'and Oholibamah bore Jeush, Jalam, and Korah. These are the sons of Esau who were born to him in the land of Canaan.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 6, 'Then Esau took his wives, his sons, his daughters, and all the members of his household, his livestock, all his beasts, and all his property that he had acquired in the land of Canaan. He went into a land away from his brother Jacob.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 7, 'For their possessions were too great for them to dwell together. The land of their sojournings could not support them because of their livestock.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 8, 'So Esau settled in the hill country of Seir. (Esau is Edom.)', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 9, 'These are the generations of Esau the father of the Edomites in the hill country of Seir.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 10, 'These are the names of Esau''s sons: Eliphaz the son of Adah the wife of Esau, Reuel the son of Basemath the wife of Esau.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 11, 'The sons of Eliphaz were Teman, Omar, Zepho, Gatam, and Kenaz.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 12, '(Timna was a concubine of Eliphaz, Esau''s son; she bore Amalek to Eliphaz.) These are the sons of Adah, Esau''s wife.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 13, 'These are the sons of Reuel: Nahath, Zerah, Shammah, and Mizzah. These are the sons of Basemath, Esau''s wife.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 14, 'These are the sons of Oholibamah the daughter of Anah the daughter of Zibeon, Esau''s wife: she bore to Esau Jeush, Jalam, and Korah.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 15, 'These are the chiefs of the sons of Esau. The sons of Eliphaz the firstborn of Esau: the chiefs Teman, Omar, Zepho, Kenaz,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 16, 'Korah, Gatam, and Amalek; these are the chiefs of Eliphaz in the land of Edom; these are the sons of Adah.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 17, 'These are the sons of Reuel, Esau''s son: the chiefs Nahath, Zerah, Shammah, and Mizzah; these are the chiefs of Reuel in the land of Edom; these are the sons of Basemath, Esau''s wife.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 18, 'These are the sons of Oholibamah, Esau''s wife: the chiefs Jeush, Jalam, and Korah; these are the chiefs born of Oholibamah the daughter of Anah, Esau''s wife.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 19, 'These are the sons of Esau (that is, Edom), and these are their chiefs.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 20, 'These are the sons of Seir the Horite, the inhabitants of the land: Lotan, Shobal, Zibeon, Anah,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 21, 'Dishon, Ezer, and Dishan; these are the chiefs of the Horites, the sons of Seir in the land of Edom.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 22, 'The sons of Lotan were Hori and Hemam; and Lotan''s sister was Timna.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 23, 'These are the sons of Shobal: Alvan, Manahath, Ebal, Shepho, and Onam.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 24, 'These are the sons of Zibeon: Aiah and Anah; he is the Anah who found the hot springs in the wilderness, as he pastured the donkeys of Zibeon his father.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 25, 'These are the children of Anah: Dishon and Oholibamah the daughter of Anah.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 26, 'These are the sons of Dishon: Hemdan, Eshban, Ithran, and Cheran.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 27, 'These are the sons of Ezer: Bilhan, Zaavan, and Akan.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 28, 'These are the sons of Dishan: Uz and Aran.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 29, 'These are the chiefs of the Horites: the chiefs Lotan, Shobal, Zibeon, Anah,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 30, 'Dishon, Ezer, and Dishan; these are the chiefs of the Horites, chief by chief in the land of Seir.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 31, 'These are the kings who reigned in the land of Edom, before any king reigned over the Israelites.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 32, 'Bela the son of Beor reigned in Edom, the name of his city being Dinhabah.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 33, 'Bela died, and Jobab the son of Zerah of Bozrah reigned in his place.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 34, 'Jobab died, and Husham of the land of the Temanites reigned in his place.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 35, 'Husham died, and Hadad the son of Bedad, who defeated Midian in the country of Moab, reigned in his place, the name of his city being Avith.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 36, 'Hadad died, and Samlah of Masrekah reigned in his place.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 37, 'Samlah died, and Shaul of Rehoboth on the Euphrates reigned in his place.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 38, 'Shaul died, and Baal-hanan the son of Achbor reigned in his place.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 39, 'Baal-hanan the son of Achbor died, and Hadar reigned in his place, the name of his city being Pau; his wife''s name was Mehetabel, the daughter of Matred, daughter of Mezahab.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 40, 'These are the names of the chiefs of Esau, according to their clans and their dwelling places, by their names: the chiefs Timna, Alvah, Jetheth,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 41, 'Oholibamah, Elah, Pinon,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 42, 'Kenaz, Teman, Mibzar,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 36, 43, 'Magdiel, and Iram; these are the chiefs of Edom (that is, Esau, the father of Edom), according to their dwelling places in the land of their possession.', NULL, 'ESV')
ON CONFLICT (book_id, chapter_number, verse_number, translation_code)
DO UPDATE SET verse_text = EXCLUDED.verse_text, section_heading = EXCLUDED.section_heading;

-- Chapter 37: Joseph's Dreams
INSERT INTO bible_verses (book_id, book_name, book_order, chapter_number, verse_number, verse_text, section_heading, translation_code)
VALUES
('genesis', 'Genesis', 1, 37, 1, 'Jacob lived in the land of his father''s sojournings, in the land of Canaan.', 'Joseph''s Dreams', 'ESV'),
('genesis', 'Genesis', 1, 37, 2, 'These are the generations of Jacob. Joseph, being seventeen years old, was pasturing the flock with his brothers. He was a boy with the sons of Bilhah and Zilpah, his father''s wives. And Joseph brought a bad report of them to their father.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 3, 'Now Israel loved Joseph more than any other of his sons, because he was the son of his old age. And he made him a robe of many colors.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 4, 'But when his brothers saw that their father loved him more than all his brothers, they hated him and could not speak peacefully to him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 5, 'Now Joseph had a dream, and when he told it to his brothers they hated him even more.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 6, 'He said to them, "Hear this dream that I have dreamed:', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 7, 'Behold, we were binding sheaves in the field, and behold, my sheaf arose and stood upright. And behold, your sheaves gathered around it and bowed down to my sheaf."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 8, 'His brothers said to him, "Are you indeed to reign over us? Or are you indeed to rule over us?" So they hated him even more for his dreams and for his words.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 9, 'Then he dreamed another dream and told it to his brothers and said, "Behold, I have dreamed another dream. Behold, the sun, the moon, and eleven stars were bowing down to me."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 10, 'But when he told it to his father and to his brothers, his father rebuked him and said to him, "What is this dream that you have dreamed? Shall I and your mother and your brothers indeed come to bow ourselves to the ground before you?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 11, 'And his brothers were jealous of him, but his father kept the saying in mind.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 12, 'Now his brothers went to pasture their father''s flock near Shechem.', 'Joseph Sold by His Brothers', 'ESV'),
('genesis', 'Genesis', 1, 37, 13, 'And Israel said to Joseph, "Are not your brothers pasturing the flock at Shechem? Come, I will send you to them." And he said to him, "Here I am."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 14, 'So he said to him, "Go now, see if it is well with your brothers and with the flock, and bring me word." So he sent him from the Valley of Hebron, and he came to Shechem.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 15, 'And a man found him wandering in the fields. And the man asked him, "What are you seeking?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 16, '"I am seeking my brothers," he said. "Tell me, please, where they are pasturing the flock."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 17, 'And the man said, "They have gone away, for I heard them say, ''Let us go to Dothan.''" So Joseph went after his brothers and found them at Dothan.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 18, 'They saw him from afar, and before he came near to them they conspired against him to kill him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 19, 'They said to one another, "Here comes this dreamer.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 20, 'Come now, let us kill him and throw him into one of the pits. Then we will say that a fierce animal has devoured him, and we will see what will become of his dreams."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 21, 'But when Reuben heard it, he rescued him out of their hands, saying, "Let us not take his life."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 22, 'And Reuben said to them, "Shed no blood; throw him into this pit here in the wilderness, but do not lay a hand on him"—that he might rescue him out of their hand to restore him to his father.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 23, 'So when Joseph came to his brothers, they stripped him of his robe, the robe of many colors that he wore.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 24, 'And they took him and threw him into a pit. The pit was empty; there was no water in it.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 25, 'Then they sat down to eat. And looking up they saw a caravan of Ishmaelites coming from Gilead, with their camels bearing gum, balm, and myrrh, on their way to carry it down to Egypt.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 26, 'Then Judah said to his brothers, "What profit is it if we kill our brother and conceal his blood?', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 27, 'Come, let us sell him to the Ishmaelites, and let not our hand be upon him, for he is our brother, our own flesh." And his brothers listened to him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 28, 'Then Midianite traders passed by. And they drew Joseph up and lifted him out of the pit, and sold him to the Ishmaelites for twenty shekels of silver. They took Joseph to Egypt.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 29, 'When Reuben returned to the pit and saw that Joseph was not in the pit, he tore his clothes', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 30, 'and returned to his brothers and said, "The boy is gone, and I, where shall I go?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 31, 'Then they took Joseph''s robe and slaughtered a goat and dipped the robe in the blood.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 32, 'And they sent the robe of many colors and brought it to their father and said, "This we have found; please identify whether it is your son''s robe or not."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 33, 'And he identified it and said, "It is my son''s robe. A fierce animal has devoured him. Joseph is without doubt torn to pieces."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 34, 'Then Jacob tore his garments and put sackcloth on his loins and mourned for his son many days.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 35, 'All his sons and all his daughters rose up to comfort him, but he refused to be comforted and said, "No, I shall go down to Sheol to my son, mourning." Thus his father wept for him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 37, 36, 'Meanwhile the Midianites had sold him in Egypt to Potiphar, an officer of Pharaoh, the captain of the guard.', NULL, 'ESV')
ON CONFLICT (book_id, chapter_number, verse_number, translation_code)
DO UPDATE SET verse_text = EXCLUDED.verse_text, section_heading = EXCLUDED.section_heading;
