-- Migration: Insert Genesis Chapters 38-41 (ESV)
-- Judah and Tamar, Joseph and Potiphar's Wife, Joseph Interprets Dreams, Joseph Rises to Power

INSERT INTO bible_verses (book_id, book_name, book_order, chapter_number, verse_number, verse_text, section_heading, translation_code)
VALUES
-- Chapter 38: Judah and Tamar
('genesis', 'Genesis', 1, 38, 1, 'It happened at that time that Judah went down from his brothers and turned aside to a certain Adullamite, whose name was Hirah.', 'Judah and Tamar', 'ESV'),
('genesis', 'Genesis', 1, 38, 2, 'There Judah saw the daughter of a certain Canaanite whose name was Shua. He took her and went in to her,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 3, 'and she conceived and bore a son, and he called his name Er.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 4, 'She conceived again and bore a son, and she called his name Onan.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 5, 'Yet again she bore a son, and she called his name Shelah. Judah was in Chezib when she bore him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 6, 'And Judah took a wife for Er his firstborn, and her name was Tamar.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 7, 'But Er, Judah''s firstborn, was wicked in the sight of the LORD, and the LORD put him to death.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 8, 'Then Judah said to Onan, "Go in to your brother''s wife and perform the duty of a brother-in-law to her, and raise up offspring for your brother."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 9, 'But Onan knew that the offspring would not be his. So whenever he went in to his brother''s wife he would waste the semen on the ground, so as not to give offspring to his brother.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 10, 'And what he did was wicked in the sight of the LORD, and he put him to death also.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 11, 'Then Judah said to Tamar his daughter-in-law, "Remain a widow in your father''s house, till Shelah my son grows up"—for he feared that he would die, like his brothers. So Tamar went and remained in her father''s house.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 12, 'In the course of time the wife of Judah, Shua''s daughter, died. When Judah was comforted, he went up to Timnah to his sheepshearers, he and his friend Hirah the Adullamite.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 13, 'And when Tamar was told, "Your father-in-law is going up to Timnah to shear his sheep,"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 14, 'she took off her widow''s garments and covered herself with a veil, wrapping herself up, and sat at the entrance to Enaim, which is on the road to Timnah. For she saw that Shelah was grown up, and she had not been given to him in marriage.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 15, 'When Judah saw her, he thought she was a prostitute, for she had covered her face.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 16, 'He turned to her at the roadside and said, "Come, let me come in to you," for he did not know that she was his daughter-in-law. She said, "What will you give me, that you may come in to me?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 17, 'He answered, "I will send you a young goat from the flock." And she said, "If you give me a pledge, until you send it—"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 18, 'He said, "What pledge shall I give you?" She replied, "Your signet and your cord and your staff that is in your hand." So he gave them to her and went in to her, and she conceived by him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 19, 'Then she arose and went away, and taking off her veil she put on the garments of her widowhood.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 20, 'When Judah sent the young goat by his friend the Adullamite to take back the pledge from the woman''s hand, he did not find her.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 21, 'And he asked the men of the place, "Where is the cult prostitute who was at Enaim at the roadside?" And they said, "No cult prostitute has been here."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 22, 'So he returned to Judah and said, "I have not found her. Also, the men of the place said, ''No cult prostitute has been here.''"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 23, 'And Judah replied, "Let her keep the things as her own, or we shall be laughed at. You see, I sent this young goat, and you did not find her."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 24, 'About three months later Judah was told, "Tamar your daughter-in-law has been immoral. Moreover, she is pregnant by immorality." And Judah said, "Bring her out, and let her be burned."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 25, 'As she was being brought out, she sent word to her father-in-law, "By the man to whom these belong, I am pregnant." And she said, "Please identify whose these are, the signet and the cord and the staff."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 26, 'Then Judah identified them and said, "She is more righteous than I, since I did not give her to my son Shelah." And he did not know her again.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 27, 'When the time of her labor came, there were twins in her womb.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 28, 'And when she was in labor, one put out a hand, and the midwife took and tied a scarlet thread on his hand, saying, "This one came out first."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 29, 'But as he drew back his hand, behold, his brother came out. And she said, "What a breach you have made for yourself!" Therefore his name was called Perez.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 38, 30, 'Afterward his brother came out with the scarlet thread on his hand, and his name was called Zerah.', NULL, 'ESV'),

-- Chapter 39: Joseph and Potiphar's Wife
('genesis', 'Genesis', 1, 39, 1, 'Now Joseph had been brought down to Egypt, and Potiphar, an officer of Pharaoh, the captain of the guard, an Egyptian, had bought him from the Ishmaelites who had brought him down there.', 'Joseph and Potiphar''s Wife', 'ESV'),
('genesis', 'Genesis', 1, 39, 2, 'The LORD was with Joseph, and he became a successful man, and he was in the house of his Egyptian master.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 39, 3, 'His master saw that the LORD was with him and that the LORD caused all that he did to succeed in his hands.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 39, 4, 'So Joseph found favor in his sight and attended him, and he made him overseer of his house and put him in charge of all that he had.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 39, 5, 'From the time that he made him overseer in his house and over all that he had the LORD blessed the Egyptian''s house for Joseph''s sake; the blessing of the LORD was on all that he had, in house and field.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 39, 6, 'So he left all that he had in Joseph''s charge, and because of him he had no concern about anything but the food he ate. Now Joseph was handsome in form and appearance.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 39, 7, 'And after a time his master''s wife cast her eyes on Joseph and said, "Lie with me."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 39, 8, 'But he refused and said to his master''s wife, "Behold, because of me my master has no concern about anything in the house, and he has put everything that he has in my charge.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 39, 9, 'He is not greater in this house than I am, nor has he kept back anything from me except yourself, because you are his wife. How then can I do this great wickedness and sin against God?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 39, 10, 'And as she spoke to Joseph day after day, he would not listen to her, to lie beside her or to be with her.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 39, 11, 'But one day, when he went into the house to do his work and none of the men of the house was there in the house,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 39, 12, 'she caught him by his garment, saying, "Lie with me." But he left his garment in her hand and fled and got out of the house.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 39, 13, 'And as soon as she saw that he had left his garment in her hand and had fled out of the house,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 39, 14, 'she called to the men of her household and said to them, "See, he has brought among us a Hebrew to laugh at us. He came in to me to lie with me, and I cried out with a loud voice.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 39, 15, 'And as soon as he heard that I lifted up my voice and cried out, he left his garment beside me and fled and got out of the house."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 39, 16, 'Then she laid up his garment by her until his master came home,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 39, 17, 'and she told him the same story, saying, "The Hebrew servant, whom you have brought among us, came in to me to laugh at me.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 39, 18, 'But as soon as I lifted up my voice and cried, he left his garment beside me and fled out of the house."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 39, 19, 'As soon as his master heard the words that his wife spoke to him, "This is the way your servant treated me," his anger was kindled.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 39, 20, 'And Joseph''s master took him and put him into the prison, the place where the king''s prisoners were confined, and he was there in prison.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 39, 21, 'But the LORD was with Joseph and showed him steadfast love and gave him favor in the sight of the keeper of the prison.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 39, 22, 'And the keeper of the prison put Joseph in charge of all the prisoners who were in the prison. Whatever was done there, he was the one who did it.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 39, 23, 'The keeper of the prison paid no attention to anything that was in Joseph''s charge, because the LORD was with him. And whatever he did, the LORD made it succeed.', NULL, 'ESV'),

-- Chapter 40: Joseph Interprets Two Prisoners' Dreams
('genesis', 'Genesis', 1, 40, 1, 'Some time after this, the cupbearer of the king of Egypt and his baker committed an offense against their lord the king of Egypt.', 'Joseph Interprets Two Prisoners'' Dreams', 'ESV'),
('genesis', 'Genesis', 1, 40, 2, 'And Pharaoh was angry with his two officers, the chief cupbearer and the chief baker,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 40, 3, 'and he put them in custody in the house of the captain of the guard, in the prison where Joseph was confined.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 40, 4, 'The captain of the guard appointed Joseph to be with them, and he attended them. They continued for some time in custody.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 40, 5, 'And one night they both dreamed—the cupbearer and the baker of the king of Egypt, who were confined in the prison—each his own dream, and each dream with its own interpretation.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 40, 6, 'When Joseph came to them in the morning, he saw that they were troubled.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 40, 7, 'So he asked Pharaoh''s officers who were with him in custody in his master''s house, "Why are your faces downcast today?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 40, 8, 'They said to him, "We have had dreams, and there is no one to interpret them." And Joseph said to them, "Do not interpretations belong to God? Please tell them to me."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 40, 9, 'So the chief cupbearer told his dream to Joseph and said to him, "In my dream there was a vine before me,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 40, 10, 'and on the vine there were three branches. As soon as it budded, its blossoms shot forth, and the clusters ripened into grapes.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 40, 11, 'Pharaoh''s cup was in my hand, and I took the grapes and pressed them into Pharaoh''s cup and placed the cup in Pharaoh''s hand."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 40, 12, 'Then Joseph said to him, "This is its interpretation: the three branches are three days.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 40, 13, 'In three days Pharaoh will lift up your head and restore you to your office, and you shall place Pharaoh''s cup in his hand as formerly, when you were his cupbearer.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 40, 14, 'Only remember me, when it is well with you, and please do me the kindness to mention me to Pharaoh, and so get me out of this house.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 40, 15, 'For I was indeed stolen out of the land of the Hebrews, and here also I have done nothing that they should put me into the pit."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 40, 16, 'When the chief baker saw that the interpretation was favorable, he said to Joseph, "I also had a dream: there were three cake baskets on my head,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 40, 17, 'and in the uppermost basket there were all sorts of baked food for Pharaoh, but the birds were eating it out of the basket on my head."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 40, 18, 'And Joseph answered and said, "This is its interpretation: the three baskets are three days.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 40, 19, 'In three days Pharaoh will lift up your head—from you!—and hang you on a tree. And the birds will eat the flesh from you."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 40, 20, 'On the third day, which was Pharaoh''s birthday, he made a feast for all his servants and lifted up the head of the chief cupbearer and the head of the chief baker among his servants.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 40, 21, 'He restored the chief cupbearer to his position, and he placed the cup in Pharaoh''s hand.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 40, 22, 'But he hanged the chief baker, as Joseph had interpreted to them.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 40, 23, 'Yet the chief cupbearer did not remember Joseph, but forgot him.', NULL, 'ESV'),

-- Chapter 41: Joseph Interprets Pharaoh's Dreams
('genesis', 'Genesis', 1, 41, 1, 'After two whole years, Pharaoh dreamed that he was standing by the Nile,', 'Joseph Interprets Pharaoh''s Dreams', 'ESV'),
('genesis', 'Genesis', 1, 41, 2, 'and behold, there came up out of the Nile seven cows attractive and plump, and they fed in the reed grass.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 3, 'And behold, seven other cows, ugly and thin, came up out of the Nile after them, and stood by the other cows on the bank of the Nile.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 4, 'And the ugly, thin cows ate up the seven attractive, plump cows. And Pharaoh awoke.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 5, 'And he fell asleep and dreamed a second time. And behold, seven ears of grain, plump and good, were growing on one stalk.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 6, 'And behold, after them sprouted seven ears, thin and blighted by the east wind.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 7, 'And the thin ears swallowed up the seven plump, full ears. And Pharaoh awoke, and behold, it was a dream.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 8, 'So in the morning his spirit was troubled, and he sent and called for all the magicians of Egypt and all its wise men. Pharaoh told them his dreams, but there was none who could interpret them to Pharaoh.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 9, 'Then the chief cupbearer said to Pharaoh, "I remember my offenses today.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 10, 'When Pharaoh was angry with his servants and put me and the chief baker in custody in the house of the captain of the guard,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 11, 'we dreamed on the same night, he and I, each having a dream with its own interpretation.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 12, 'A young Hebrew was there with us, a servant of the captain of the guard. When we told him, he interpreted our dreams to us, giving an interpretation to each man according to his dream.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 13, 'And as he interpreted to us, so it came about. I was restored to my office, and the baker was hanged."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 14, 'Then Pharaoh sent and called Joseph, and they quickly brought him out of the pit. And when he had shaved himself and changed his clothes, he came in before Pharaoh.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 15, 'And Pharaoh said to Joseph, "I have had a dream, and there is no one who can interpret it. I have heard it said of you that when you hear a dream you can interpret it."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 16, 'Joseph answered Pharaoh, "It is not in me; God will give Pharaoh a favorable answer."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 17, 'Then Pharaoh said to Joseph, "Behold, in my dream I was standing on the banks of the Nile.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 18, 'Seven cows, plump and attractive, came up out of the Nile and fed in the reed grass.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 19, 'Seven other cows came up after them, poor and very ugly and thin, such as I had never seen in all the land of Egypt.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 20, 'And the thin, ugly cows ate up the first seven plump cows,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 21, 'but when they had eaten them no one would have known that they had eaten them, for they were still as ugly as at the beginning. Then I awoke.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 22, 'I also saw in my dream seven ears growing on one stalk, full and good.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 23, 'Seven ears, withered, thin, and blighted by the east wind, sprouted after them,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 24, 'and the thin ears swallowed up the seven good ears. And I told it to the magicians, but there was no one who could explain it to me."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 25, 'Then Joseph said to Pharaoh, "The dreams of Pharaoh are one; God has revealed to Pharaoh what he is about to do.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 26, 'The seven good cows are seven years, and the seven good ears are seven years; the dreams are one.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 27, 'The seven lean and ugly cows that came up after them are seven years, and the seven empty ears blighted by the east wind are also seven years of famine.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 28, 'It is as I told Pharaoh; God has shown to Pharaoh what he is about to do.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 29, 'There will come seven years of great plenty throughout all the land of Egypt,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 30, 'but after them there will arise seven years of famine, and all the plenty will be forgotten in the land of Egypt. The famine will consume the land,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 31, 'and the plenty will be unknown in the land by reason of the famine that will follow, for it will be very severe.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 32, 'And the doubling of Pharaoh''s dream means that the thing is fixed by God, and God will shortly bring it about.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 33, 'Now therefore let Pharaoh select a discerning and wise man, and set him over the land of Egypt.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 34, 'Let Pharaoh proceed to appoint overseers over the land and take one-fifth of the produce of the land of Egypt during the seven plentiful years.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 35, 'And let them gather all the food of these good years that are coming and store up grain under the authority of Pharaoh for food in the cities, and let them keep it.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 36, 'That food shall be a reserve for the land against the seven years of famine that are to occur in the land of Egypt, so that the land may not perish through the famine."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 37, 'This proposal pleased Pharaoh and all his servants.', 'Joseph Rises to Power', 'ESV'),
('genesis', 'Genesis', 1, 41, 38, 'And Pharaoh said to his servants, "Can we find a man like this, in whom is the Spirit of God?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 39, 'Then Pharaoh said to Joseph, "Since God has shown you all this, there is none so discerning and wise as you are.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 40, 'You shall be over my house, and all my people shall order themselves as you command. Only as regards the throne will I be greater than you."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 41, 'And Pharaoh said to Joseph, "See, I have set you over all the land of Egypt."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 42, 'Then Pharaoh took his signet ring from his hand and put it on Joseph''s hand, and clothed him in garments of fine linen and put a gold chain about his neck.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 43, 'And he made him ride in his second chariot. And they called out before him, "Bow the knee!" Thus he set him over all the land of Egypt.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 44, 'Moreover, Pharaoh said to Joseph, "I am Pharaoh, and without your consent no one shall lift up hand or foot in all the land of Egypt."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 45, 'And Pharaoh called Joseph''s name Zaphenath-paneah. And he gave him in marriage Asenath, the daughter of Potiphera priest of On. So Joseph went out over the land of Egypt.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 46, 'Joseph was thirty years old when he entered the service of Pharaoh king of Egypt. And Joseph went out from the presence of Pharaoh and went through all the land of Egypt.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 47, 'During the seven plentiful years the earth produced abundantly,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 48, 'and he gathered up all the food of these seven years, which occurred in the land of Egypt, and put the food in the cities. He put in every city the food from the fields around it.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 49, 'And Joseph stored up grain in great abundance, like the sand of the sea, until he ceased to measure it, for it could not be measured.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 50, 'Before the year of famine came, two sons were born to Joseph. Asenath, the daughter of Potiphera priest of On, bore them to him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 51, 'Joseph called the name of the firstborn Manasseh. "For," he said, "God has made me forget all my hardship and all my father''s house."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 52, 'The name of the second he called Ephraim, "For God has made me fruitful in the land of my affliction."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 53, 'The seven years of plenty that occurred in the land of Egypt came to an end,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 54, 'and the seven years of famine began to come, as Joseph had said. There was famine in all lands, but in all the land of Egypt there was bread.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 55, 'When all the land of Egypt was famished, the people cried to Pharaoh for bread. Pharaoh said to all the Egyptians, "Go to Joseph. What he says to you, do."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 56, 'So when the famine had spread over all the land, Joseph opened all the storehouses and sold to the Egyptians, for the famine was severe in the land of Egypt.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 41, 57, 'Moreover, all the earth came to Egypt to Joseph to buy grain, because the famine was severe over all the earth.', NULL, 'ESV')

ON CONFLICT (book_id, chapter_number, verse_number, translation_code)
DO UPDATE SET verse_text = EXCLUDED.verse_text, section_heading = EXCLUDED.section_heading;
