-- Migration: Insert Genesis Chapters 42-50 (ESV)
-- Joseph's Brothers Go to Egypt through The Death of Joseph

INSERT INTO bible_verses (book_id, book_name, book_order, chapter_number, verse_number, verse_text, section_heading, translation_code)
VALUES
-- Chapter 42: Joseph's Brothers Go to Egypt
('genesis', 'Genesis', 1, 42, 1, 'When Jacob learned that there was grain for sale in Egypt, he said to his sons, "Why do you look at one another?"', 'Joseph''s Brothers Go to Egypt', 'ESV'),
('genesis', 'Genesis', 1, 42, 2, 'And he said, "Behold, I have heard that there is grain for sale in Egypt. Go down and buy grain for us there, that we may live and not die."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 3, 'So ten of Joseph''s brothers went down to buy grain in Egypt.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 4, 'But Jacob did not send Benjamin, Joseph''s brother, with his brothers, for he feared that harm might happen to him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 5, 'Thus the sons of Israel came to buy among the others who came, for the famine was in the land of Canaan.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 6, 'Now Joseph was governor over the land. He was the one who sold to all the people of the land. And Joseph''s brothers came and bowed themselves before him with their faces to the ground.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 7, 'Joseph saw his brothers and recognized them, but he treated them like strangers and spoke roughly to them. "Where do you come from?" he said. They said, "From the land of Canaan, to buy food."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 8, 'And Joseph recognized his brothers, but they did not recognize him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 9, 'And Joseph remembered the dreams that he had dreamed of them. And he said to them, "You are spies; you have come to see the nakedness of the land."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 10, 'They said to him, "No, my lord, your servants have come to buy food.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 11, 'We are all sons of one man. We are honest men. Your servants have never been spies."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 12, 'He said to them, "No, it is the nakedness of the land that you have come to see."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 13, 'And they said, "We, your servants, are twelve brothers, the sons of one man in the land of Canaan, and behold, the youngest is this day with our father, and one is no more."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 14, 'But Joseph said to them, "It is as I said to you. You are spies.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 15, 'By this you shall be tested: by the life of Pharaoh, you shall not go from this place unless your youngest brother comes here.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 16, 'Send one of you, and let him bring your brother, while you remain confined, that your words may be tested, whether there is truth in you. Or else, by the life of Pharaoh, surely you are spies."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 17, 'And he put them all together in custody for three days.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 18, 'On the third day Joseph said to them, "Do this and you will live, for I fear God:', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 19, 'if you are honest men, let one of your brothers remain confined where you are in custody, and let the rest go and carry grain for the famine of your households,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 20, 'and bring your youngest brother to me. So your words will be verified, and you shall not die." And they did so.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 21, 'Then they said to one another, "In truth we are guilty concerning our brother, in that we saw the distress of his soul, when he begged us and we did not listen. That is why this distress has come upon us."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 22, 'And Reuben answered them, "Did I not tell you not to sin against the boy? But you did not listen. So now there comes a reckoning for his blood."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 23, 'They did not know that Joseph understood them, for there was an interpreter between them.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 24, 'Then he turned away from them and wept. And he returned to them and spoke to them. And he took Simeon from them and bound him before their eyes.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 25, 'And Joseph gave orders to fill their bags with grain, and to replace every man''s money in his sack, and to give them provisions for the journey. This was done for them.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 26, 'Then they loaded their donkeys with their grain and departed.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 27, 'And as one of them opened his sack to give his donkey fodder at the lodging place, he saw his money in the mouth of his sack.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 28, 'He said to his brothers, "My money has been put back; here it is in the mouth of my sack!" At this their hearts failed them, and they turned trembling to one another, saying, "What is this that God has done to us?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 29, 'When they came to Jacob their father in the land of Canaan, they told him all that had happened to them, saying,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 30, '"The man, the lord of the land, spoke roughly to us and took us to be spies of the land.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 31, 'But we said to him, ''We are honest men; we have never been spies.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 32, 'We are twelve brothers, sons of our father. One is no more, and the youngest is this day with our father in the land of Canaan.''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 33, 'Then the man, the lord of the land, said to us, ''By this I shall know that you are honest men: leave one of your brothers with me, and take grain for the famine of your households, and go your way.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 34, 'Bring your youngest brother to me. Then I shall know that you are not spies but honest men, and I will deliver your brother to you, and you shall trade in the land.''"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 35, 'As they emptied their sacks, behold, every man''s bundle of money was in his sack. And when they and their father saw their bundles of money, they were afraid.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 36, 'And Jacob their father said to them, "You have bereaved me of my children: Joseph is no more, and Simeon is no more, and now you would take Benjamin. All this has come against me."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 37, 'Then Reuben said to his father, "Kill my two sons if I do not bring him back to you. Put him in my hands, and I will bring him back to you."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 42, 38, 'But he said, "My son shall not go down with you, for his brother is dead, and he is the only one left. If harm should happen to him on the journey that you are to make, you would bring down my gray hairs with sorrow to Sheol."', NULL, 'ESV'),

-- Chapter 43: Joseph's Brothers Return to Egypt
('genesis', 'Genesis', 1, 43, 1, 'Now the famine was severe in the land.', 'Joseph''s Brothers Return to Egypt', 'ESV'),
('genesis', 'Genesis', 1, 43, 2, 'And when they had eaten the grain that they had brought from Egypt, their father said to them, "Go again, buy us a little food."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 3, 'But Judah said to him, "The man solemnly warned us, saying, ''You shall not see my face unless your brother is with you.''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 4, 'If you will send our brother with us, we will go down and buy you food.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 5, 'But if you will not send him, we will not go down, for the man said to us, ''You shall not see my face, unless your brother is with you.''"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 6, 'Israel said, "Why did you treat me so badly as to tell the man that you had another brother?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 7, 'They replied, "The man questioned us carefully about ourselves and our kindred, saying, ''Is your father still alive? Do you have another brother?'' What we told him was in answer to these questions. Could we in any way know that he would say, ''Bring your brother down''?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 8, 'And Judah said to Israel his father, "Send the boy with me, and we will arise and go, that we may live and not die, both we and you and also our little ones.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 9, 'I will be a pledge of his safety. From my hand you shall require him. If I do not bring him back to you and set him before you, then let me bear the blame forever.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 10, 'If we had not delayed, we would now have returned twice."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 11, 'Then their father Israel said to them, "If it must be so, then do this: take some of the choice fruits of the land in your bags, and carry a present down to the man, a little balm and a little honey, gum, myrrh, pistachio nuts, and almonds.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 12, 'Take double the money with you. Carry back with you the money that was returned in the mouth of your sacks. Perhaps it was an oversight.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 13, 'Take also your brother, and arise, go again to the man.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 14, 'May God Almighty grant you mercy before the man, and may he send back your other brother and Benjamin. And as for me, if I am bereaved of my children, I am bereaved."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 15, 'So the men took this present, and they took double the money with them, and Benjamin. They arose and went down to Egypt and stood before Joseph.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 16, 'When Joseph saw Benjamin with them, he said to the steward of his house, "Bring the men into the house, and slaughter an animal and make ready, for the men are to dine with me at noon."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 17, 'The man did as Joseph told him and brought the men to Joseph''s house.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 18, 'And the men were afraid because they were brought to Joseph''s house, and they said, "It is because of the money, which was replaced in our sacks the first time, that we are brought in, so that he may assault us and fall upon us to make us servants and seize our donkeys."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 19, 'So they went up to the steward of Joseph''s house and spoke with him at the door of the house,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 20, 'and said, "Oh, my lord, we came down the first time to buy food.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 21, 'And when we came to the lodging place we opened our sacks, and there was each man''s money in the mouth of his sack, our money in full weight. So we have brought it again with us,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 22, 'and we have brought other money down with us to buy food. We do not know who put our money in our sacks."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 23, 'He replied, "Peace to you, do not be afraid. Your God and the God of your father has put treasure in your sacks for you. I received your money." Then he brought Simeon out to them.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 24, 'And when the man had brought the men into Joseph''s house and given them water, and they had washed their feet, and when he had given their donkeys fodder,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 25, 'they prepared the present for Joseph''s coming at noon, for they heard that they should eat bread there.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 26, 'When Joseph came home, they brought into the house to him the present that they had with them and bowed down to him to the ground.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 27, 'And he inquired about their welfare and said, "Is your father well, the old man of whom you spoke? Is he still alive?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 28, 'They said, "Your servant our father is well; he is still alive." And they bowed their heads and prostrated themselves.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 29, 'And he lifted up his eyes and saw his brother Benjamin, his mother''s son, and said, "Is this your youngest brother, of whom you spoke to me? God be gracious to you, my son!"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 30, 'Then Joseph hurried out, for his compassion grew warm for his brother, and he sought a place to weep. And he entered his chamber and wept there.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 31, 'Then he washed his face and came out. And controlling himself he said, "Serve the food."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 32, 'They served him by himself, and them by themselves, and the Egyptians who ate with him by themselves, because the Egyptians could not eat with the Hebrews, for that is an abomination to the Egyptians.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 33, 'And they sat before him, the firstborn according to his birthright and the youngest according to his youth. And the men looked at one another in amazement.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 43, 34, 'Portions were taken to them from Joseph''s table, but Benjamin''s portion was five times as much as any of theirs. And they drank and were merry with him.', NULL, 'ESV'),

-- Chapter 44: Joseph Tests His Brothers
('genesis', 'Genesis', 1, 44, 1, 'Then he commanded the steward of his house, "Fill the men''s sacks with food, as much as they can carry, and put each man''s money in the mouth of his sack,', 'Joseph Tests His Brothers', 'ESV'),
('genesis', 'Genesis', 1, 44, 2, 'and put my cup, the silver cup, in the mouth of the sack of the youngest, with his money for the grain." And he did as Joseph told him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 3, 'As soon as the morning was light, the men were sent away with their donkeys.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 4, 'They had gone only a short distance from the city. Now Joseph said to his steward, "Up, follow after the men, and when you overtake them, say to them, ''Why have you repaid evil for good?', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 5, 'Is it not from this that my lord drinks, and by this that he practices divination? You have done evil in doing this.''"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 6, 'When he overtook them, he spoke to them these words.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 7, 'They said to him, "Why does my lord speak such words as these? Far be it from your servants to do such a thing!', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 8, 'Behold, the money that we found in the mouths of our sacks we brought back to you from the land of Canaan. How then could we steal silver or gold from your lord''s house?', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 9, 'Whichever of your servants is found with it shall die, and we also will be my lord''s servants."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 10, 'He said, "Let it be as you say: he who is found with it shall be my servant, and the rest of you shall be innocent."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 11, 'Then each man quickly lowered his sack to the ground, and each man opened his sack.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 12, 'And he searched, beginning with the eldest and ending with the youngest. And the cup was found in Benjamin''s sack.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 13, 'Then they tore their clothes, and every man loaded his donkey, and they returned to the city.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 14, 'When Judah and his brothers came to Joseph''s house, he was still there. They fell before him to the ground.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 15, 'Joseph said to them, "What deed is this that you have done? Do you not know that a man like me can indeed practice divination?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 16, 'And Judah said, "What shall we say to my lord? What shall we speak? Or how can we clear ourselves? God has found out the guilt of your servants; behold, we are my lord''s servants, both we and he also in whose hand the cup has been found."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 17, 'But he said, "Far be it from me that I should do so! Only the man in whose hand the cup was found shall be my servant. But as for you, go up in peace to your father."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 18, 'Then Judah went up to him and said, "Oh, my lord, please let your servant speak a word in my lord''s ears, and let not your anger burn against your servant, for you are like Pharaoh himself.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 19, 'My lord asked his servants, saying, ''Have you a father, or a brother?''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 20, 'And we said to my lord, ''We have a father, an old man, and a young brother, the child of his old age. His brother is dead, and he alone is left of his mother''s children, and his father loves him.''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 21, 'Then you said to your servants, ''Bring him down to me, that I may set my eyes on him.''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 22, 'We said to my lord, ''The boy cannot leave his father, for if he should leave his father, his father would die.''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 23, 'Then you said to your servants, ''Unless your youngest brother comes down with you, you shall not see my face again.''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 24, '"When we went back to your servant my father, we told him the words of my lord.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 25, 'And when our father said, ''Go again, buy us a little food,''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 26, 'we said, ''We cannot go down. If our youngest brother goes with us, then we will go down. For we cannot see the man''s face unless our youngest brother is with us.''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 27, 'Then your servant my father said to us, ''You know that my wife bore me two sons.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 28, 'One left me, and I said, Surely he has been torn to pieces, and I have never seen him since.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 29, 'If you take this one also from me, and harm happens to him, you will bring down my gray hairs in evil to Sheol.''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 30, '"Now therefore, as soon as I come to your servant my father, and the boy is not with us, then, as his life is bound up in the boy''s life,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 31, 'as soon as he sees that the boy is not with us, he will die, and your servants will bring down the gray hairs of your servant our father with sorrow to Sheol.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 32, 'For your servant became a pledge of safety for the boy to my father, saying, ''If I do not bring him back to you, then I shall bear the blame before my father all my life.''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 33, 'Now therefore, please let your servant remain instead of the boy as a servant to my lord, and let the boy go back with his brothers.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 44, 34, 'For how can I go back to my father if the boy is not with me? I fear to see the evil that would find my father."', NULL, 'ESV'),

-- Chapter 45: Joseph Provides for His Brothers and Family
('genesis', 'Genesis', 1, 45, 1, 'Then Joseph could not control himself before all those who stood by him. He cried, "Make everyone go out from me." So no one stayed with him when Joseph made himself known to his brothers.', 'Joseph Provides for His Brothers and Family', 'ESV'),
('genesis', 'Genesis', 1, 45, 2, 'And he wept aloud, so that the Egyptians heard it, and the household of Pharaoh heard it.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 3, 'And Joseph said to his brothers, "I am Joseph! Is my father still alive?" But his brothers could not answer him, for they were dismayed at his presence.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 4, 'So Joseph said to his brothers, "Come near to me, please." And they came near. And he said, "I am your brother, Joseph, whom you sold into Egypt.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 5, 'And now do not be distressed or angry with yourselves because you sold me here, for God sent me before you to preserve life.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 6, 'For the famine has been in the land these two years, and there are yet five years in which there will be neither plowing nor harvest.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 7, 'And God sent me before you to preserve for you a remnant on earth, and to keep alive for you many survivors.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 8, 'So it was not you who sent me here, but God. He has made me a father to Pharaoh, and lord of all his house and ruler over all the land of Egypt.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 9, 'Hurry and go up to my father and say to him, ''Thus says your son Joseph, God has made me lord of all Egypt. Come down to me; do not tarry.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 10, 'You shall dwell in the land of Goshen, and you shall be near me, you and your children and your children''s children, and your flocks, your herds, and all that you have.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 11, 'There I will provide for you, for there are yet five years of famine to come, so that you and your household, and all that you have, do not come to poverty.''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 12, 'And now your eyes see, and the eyes of my brother Benjamin see, that it is my mouth that speaks to you.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 13, 'You must tell my father of all my honor in Egypt, and of all that you have seen. Hurry and bring my father down here."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 14, 'Then he fell upon his brother Benjamin''s neck and wept, and Benjamin wept upon his neck.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 15, 'And he kissed all his brothers and wept upon them. After that his brothers talked with him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 16, 'When the report was heard in Pharaoh''s house, "Joseph''s brothers have come," it pleased Pharaoh and his servants.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 17, 'And Pharaoh said to Joseph, "Say to your brothers, ''Do this: load your beasts and go back to the land of Canaan,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 18, 'and take your father and your households, and come to me, and I will give you the best of the land of Egypt, and you shall eat the fat of the land.''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 19, 'And you, Joseph, are commanded to say, ''Do this: take wagons from the land of Egypt for your little ones and for your wives, and bring your father, and come.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 20, 'Have no concern for your goods, for the best of all the land of Egypt is yours.''"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 21, 'The sons of Israel did so: and Joseph gave them wagons, according to the command of Pharaoh, and gave them provisions for the journey.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 22, 'To each and all of them he gave a change of clothes, but to Benjamin he gave three hundred shekels of silver and five changes of clothes.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 23, 'To his father he sent as follows: ten donkeys loaded with the good things of Egypt, and ten female donkeys loaded with grain, bread, and provision for his father on the journey.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 24, 'Then he sent his brothers away, and as they departed, he said to them, "Do not quarrel on the way."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 25, 'So they went up out of Egypt and came to the land of Canaan to their father Jacob.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 26, 'And they told him, "Joseph is still alive, and he is ruler over all the land of Egypt." And his heart became numb, for he did not believe them.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 27, 'But when they told him all the words of Joseph, which he had said to them, and when he saw the wagons that Joseph had sent to carry him, the spirit of their father Jacob revived.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 45, 28, 'And Israel said, "It is enough; Joseph my son is still alive. I will go and see him before I die."', NULL, 'ESV'),

-- Chapter 46: Joseph Brings His Family to Egypt
('genesis', 'Genesis', 1, 46, 1, 'So Israel took his journey with all that he had and came to Beersheba, and offered sacrifices to the God of his father Isaac.', 'Joseph Brings His Family to Egypt', 'ESV'),
('genesis', 'Genesis', 1, 46, 2, 'And God spoke to Israel in visions of the night and said, "Jacob, Jacob." And he said, "Here am I."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 3, 'Then he said, "I am God, the God of your father. Do not be afraid to go down to Egypt, for there I will make you into a great nation.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 4, 'I myself will go down with you to Egypt, and I will also bring you up again, and Joseph''s hand shall close your eyes."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 5, 'Then Jacob set out from Beersheba. The sons of Israel carried Jacob their father, their little ones, and their wives, in the wagons that Pharaoh had sent to carry him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 6, 'They also took their livestock and their goods, which they had gained in the land of Canaan, and came into Egypt, Jacob and all his offspring with him,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 7, 'his sons, and his sons'' sons with him, his daughters, and his sons'' daughters. All his offspring he brought with him into Egypt.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 8, 'Now these are the names of the descendants of Israel, who came into Egypt, Jacob and his sons. Reuben, Jacob''s firstborn,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 9, 'and the sons of Reuben: Hanoch, Pallu, Hezron, and Carmi.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 10, 'The sons of Simeon: Jemuel, Jamin, Ohad, Jachin, Zohar, and Shaul, the son of a Canaanite woman.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 11, 'The sons of Levi: Gershon, Kohath, and Merari.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 12, 'The sons of Judah: Er, Onan, Shelah, Perez, and Zerah (but Er and Onan died in the land of Canaan); and the sons of Perez were Hezron and Hamul.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 13, 'The sons of Issachar: Tola, Puvah, Yob, and Shimron.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 14, 'The sons of Zebulun: Sered, Elon, and Jahleel.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 15, 'These are the sons of Leah, whom she bore to Jacob in Paddan-aram, together with his daughter Dinah; altogether his sons and his daughters numbered thirty-three.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 16, 'The sons of Gad: Ziphion, Haggi, Shuni, Ezbon, Eri, Arodi, and Areli.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 17, 'The sons of Asher: Imnah, Ishvah, Ishvi, Beriah, with Serah their sister. And the sons of Beriah: Heber and Malchiel.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 18, 'These are the sons of Zilpah, whom Laban gave to Leah his daughter; and these she bore to Jacob—sixteen persons.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 19, 'The sons of Rachel, Jacob''s wife: Joseph and Benjamin.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 20, 'And to Joseph in the land of Egypt were born Manasseh and Ephraim, whom Asenath, the daughter of Potiphera the priest of On, bore to him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 21, 'And the sons of Benjamin: Bela, Becher, Ashbel, Gera, Naaman, Ehi, Rosh, Muppim, Huppim, and Ard.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 22, 'These are the sons of Rachel, who were born to Jacob—fourteen persons in all.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 23, 'The sons of Dan: Hushim.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 24, 'The sons of Naphtali: Jahzeel, Guni, Jezer, and Shillem.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 25, 'These are the sons of Bilhah, whom Laban gave to Rachel his daughter, and these she bore to Jacob—seven persons in all.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 26, 'All the persons belonging to Jacob who came into Egypt, who were his own descendants, not including Jacob''s sons'' wives, were sixty-six persons in all.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 27, 'And the sons of Joseph, who were born to him in Egypt, were two. All the persons of the house of Jacob who came into Egypt were seventy.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 28, 'He had sent Judah ahead of him to Joseph to show the way before him in Goshen, and they came into the land of Goshen.', 'Jacob and Joseph Reunited', 'ESV'),
('genesis', 'Genesis', 1, 46, 29, 'Then Joseph prepared his chariot and went up to meet Israel his father in Goshen. He presented himself to him and fell on his neck and wept on his neck a good while.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 30, 'Israel said to Joseph, "Now let me die, since I have seen your face and know that you are still alive."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 31, 'Joseph said to his brothers and to his father''s household, "I will go up and tell Pharaoh and will say to him, ''My brothers and my father''s household, who were in the land of Canaan, have come to me.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 32, 'And the men are shepherds, for they have been keepers of livestock, and they have brought their flocks and their herds and all that they have.''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 33, 'When Pharaoh calls you and says, ''What is your occupation?''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 46, 34, 'you shall say, ''Your servants have been keepers of livestock from our youth even until now, both we and our fathers,'' in order that you may dwell in the land of Goshen, for every shepherd is an abomination to the Egyptians."', NULL, 'ESV'),

-- Chapter 47: Jacob's Family Settles in Goshen
('genesis', 'Genesis', 1, 47, 1, 'So Joseph went in and told Pharaoh, "My father and my brothers, with their flocks and herds and all that they possess, have come from the land of Canaan. They are now in the land of Goshen."', 'Jacob''s Family Settles in Goshen', 'ESV'),
('genesis', 'Genesis', 1, 47, 2, 'And from among his brothers he took five men and presented them to Pharaoh.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 3, 'Pharaoh said to his brothers, "What is your occupation?" And they said to Pharaoh, "Your servants are shepherds, as our fathers were."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 4, 'They said to Pharaoh, "We have come to sojourn in the land, for there is no pasture for your servants'' flocks, for the famine is severe in the land of Canaan. And now, please let your servants dwell in the land of Goshen."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 5, 'Then Pharaoh said to Joseph, "Your father and your brothers have come to you.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 6, 'The land of Egypt is before you. Settle your father and your brothers in the best of the land. Let them settle in the land of Goshen, and if you know any able men among them, put them in charge of my livestock."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 7, 'Then Joseph brought in Jacob his father and stood him before Pharaoh, and Jacob blessed Pharaoh.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 8, 'And Pharaoh said to Jacob, "How many are the days of the years of your life?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 9, 'And Jacob said to Pharaoh, "The days of the years of my sojourning are 130 years. Few and evil have been the days of the years of my life, and they have not attained to the days of the years of the life of my fathers in the days of their sojourning."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 10, 'And Jacob blessed Pharaoh and went out from the presence of Pharaoh.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 11, 'Then Joseph settled his father and his brothers and gave them a possession in the land of Egypt, in the best of the land, in the land of Rameses, as Pharaoh had commanded.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 12, 'And Joseph provided his father, his brothers, and all his father''s household with food, according to the number of their dependents.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 13, 'Now there was no food in all the land, for the famine was very severe, so that the land of Egypt and the land of Canaan languished by reason of the famine.', 'Joseph and the Famine', 'ESV'),
('genesis', 'Genesis', 1, 47, 14, 'And Joseph gathered up all the money that was found in the land of Egypt and in the land of Canaan, in exchange for the grain that they bought. And Joseph brought the money into Pharaoh''s house.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 15, 'And when the money was all spent in the land of Egypt and in the land of Canaan, all the Egyptians came to Joseph and said, "Give us food. Why should we die before your eyes? For our money is gone."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 16, 'And Joseph answered, "Give your livestock, and I will give you food in exchange for your livestock, if your money is gone."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 17, 'So they brought their livestock to Joseph, and Joseph gave them food in exchange for the horses, the flocks, the herds, and the donkeys. He supplied them with food in exchange for all their livestock that year.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 18, 'And when that year was ended, they came to him the following year and said to him, "We will not hide from my lord that our money is all spent. The herds of livestock are my lord''s. There is nothing left in the sight of my lord but our bodies and our land.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 19, 'Why should we die before your eyes, both we and our land? Buy us and our land for food, and we with our land will be servants to Pharaoh. And give us seed that we may live and not die, and that the land may not be desolate."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 20, 'So Joseph bought all the land of Egypt for Pharaoh, for all the Egyptians sold their fields, because the famine was severe on them. The land became Pharaoh''s.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 21, 'As for the people, he made servants of them from one end of Egypt to the other.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 22, 'Only the land of the priests he did not buy, for the priests had a fixed allowance from Pharaoh and lived on the allowance that Pharaoh gave them; therefore they did not sell their land.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 23, 'Then Joseph said to the people, "Behold, I have this day bought you and your land for Pharaoh. Now here is seed for you, and you shall sow the land.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 24, 'And at the harvests you shall give a fifth to Pharaoh, and four fifths shall be your own, as seed for the field and as food for yourselves and your households, and as food for your little ones."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 25, 'And they said, "You have saved our lives; may it please my lord, we will be servants to Pharaoh."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 26, 'So Joseph made it a statute concerning the land of Egypt, and it stands to this day, that Pharaoh should have the fifth; the land of the priests alone did not become Pharaoh''s.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 27, 'Thus Israel settled in the land of Egypt, in the land of Goshen. And they gained possessions in it, and were fruitful and multiplied greatly.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 28, 'And Jacob lived in the land of Egypt seventeen years. So the days of Jacob, the years of his life, were 147 years.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 29, 'And when the time drew near that Israel must die, he called his son Joseph and said to him, "If now I have found favor in your sight, put your hand under my thigh and promise to deal kindly and truly with me. Do not bury me in Egypt,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 30, 'but let me lie with my fathers. Carry me out of Egypt and bury me in their burying place." He answered, "I will do as you have said."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 47, 31, 'And he said, "Swear to me"; and he swore to him. Then Israel bowed himself upon the head of his bed.', NULL, 'ESV'),

-- Chapter 48: Jacob Blesses Ephraim and Manasseh
('genesis', 'Genesis', 1, 48, 1, 'After this, Joseph was told, "Behold, your father is ill." So he took with him his two sons, Manasseh and Ephraim.', 'Jacob Blesses Ephraim and Manasseh', 'ESV'),
('genesis', 'Genesis', 1, 48, 2, 'And it was told to Jacob, "Your son Joseph has come to you." Then Israel summoned his strength and sat up in bed.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 48, 3, 'And Jacob said to Joseph, "God Almighty appeared to me at Luz in the land of Canaan and blessed me,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 48, 4, 'and said to me, ''Behold, I will make you fruitful and multiply you, and I will make of you a company of peoples and will give this land to your offspring after you for an everlasting possession.''', NULL, 'ESV'),
('genesis', 'Genesis', 1, 48, 5, 'And now your two sons, who were born to you in the land of Egypt before I came to you in Egypt, are mine; Ephraim and Manasseh shall be mine, as Reuben and Simeon are.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 48, 6, 'And the children that you fathered after them shall be yours. They shall be called by the name of their brothers in their inheritance.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 48, 7, 'As for me, when I came from Paddan, to my sorrow Rachel died in the land of Canaan on the way, when there was still some distance to go to Ephrath, and I buried her there on the way to Ephrath (that is, Bethlehem)."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 48, 8, 'When Israel saw Joseph''s sons, he said, "Who are these?"', NULL, 'ESV'),
('genesis', 'Genesis', 1, 48, 9, 'Joseph said to his father, "They are my sons, whom God has given me here." And he said, "Bring them to me, please, that I may bless them."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 48, 10, 'Now the eyes of Israel were dim with age, so that he could not see. So Joseph brought them near him, and he kissed them and embraced them.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 48, 11, 'And Israel said to Joseph, "I never expected to see your face; and behold, God has let me see your offspring also."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 48, 12, 'Then Joseph removed them from his knees, and he bowed himself with his face to the earth.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 48, 13, 'And Joseph took them both, Ephraim in his right hand toward Israel''s left hand, and Manasseh in his left hand toward Israel''s right hand, and brought them near him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 48, 14, 'And Israel stretched out his right hand and laid it on the head of Ephraim, who was the younger, and his left hand on the head of Manasseh, crossing his hands (for Manasseh was the firstborn).', NULL, 'ESV'),
('genesis', 'Genesis', 1, 48, 15, 'And he blessed Joseph and said, "The God before whom my fathers Abraham and Isaac walked, the God who has been my shepherd all my life long to this day,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 48, 16, 'the angel who has redeemed me from all evil, bless the boys; and in them let my name be carried on, and the name of my fathers Abraham and Isaac; and let them grow into a multitude in the midst of the earth."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 48, 17, 'When Joseph saw that his father laid his right hand on the head of Ephraim, it displeased him, and he took his father''s hand to move it from Ephraim''s head to Manasseh''s head.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 48, 18, 'And Joseph said to his father, "Not this way, my father; since this one is the firstborn, put your right hand on his head."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 48, 19, 'But his father refused and said, "I know, my son, I know. He also shall become a people, and he also shall be great. Nevertheless, his younger brother shall be greater than he, and his offspring shall become a multitude of nations."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 48, 20, 'So he blessed them that day, saying, "By you Israel will pronounce blessings, saying, ''God make you as Ephraim and as Manasseh.''" Thus he put Ephraim before Manasseh.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 48, 21, 'Then Israel said to Joseph, "Behold, I am about to die, but God will be with you and will bring you again to the land of your fathers.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 48, 22, 'Moreover, I have given to you rather than to your brothers one mountain slope that I took from the hand of the Amorites with my sword and with my bow."', NULL, 'ESV'),

-- Chapter 49: Jacob Blesses His Sons
('genesis', 'Genesis', 1, 49, 1, 'Then Jacob called his sons and said, "Gather yourselves together, that I may tell you what shall happen to you in days to come.', 'Jacob Blesses His Sons', 'ESV'),
('genesis', 'Genesis', 1, 49, 2, '"Assemble and listen, O sons of Jacob, listen to Israel your father.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 3, '"Reuben, you are my firstborn, my might, and the firstfruits of my strength, preeminent in dignity and preeminent in power.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 4, 'Unstable as water, you shall not have preeminence, because you went up to your father''s bed; then you defiled it—he went up to my couch!', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 5, '"Simeon and Levi are brothers; weapons of violence are their swords.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 6, 'Let my soul come not into their council; O my glory, be not joined to their company. For in their anger they killed men, and in their willfulness they hamstrung oxen.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 7, 'Cursed be their anger, for it is fierce, and their wrath, for it is cruel! I will divide them in Jacob and scatter them in Israel.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 8, '"Judah, your brothers shall praise you; your hand shall be on the neck of your enemies; your father''s sons shall bow down before you.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 9, 'Judah is a lion''s cub; from the prey, my son, you have gone up. He stooped down; he crouched as a lion and as a lioness; who dares rouse him?', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 10, 'The scepter shall not depart from Judah, nor the ruler''s staff from between his feet, until tribute comes to him; and to him shall be the obedience of the peoples.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 11, 'Binding his foal to the vine and his donkey''s colt to the choice vine, he has washed his garments in wine and his vesture in the blood of grapes.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 12, 'His eyes are darker than wine, and his teeth whiter than milk.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 13, '"Zebulun shall dwell at the shore of the sea; he shall become a haven for ships, and his border shall be at Sidon.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 14, '"Issachar is a strong donkey, crouching between the sheepfolds.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 15, 'He saw that a resting place was good, and that the land was pleasant, so he bowed his shoulder to bear, and became a servant at forced labor.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 16, '"Dan shall judge his people as one of the tribes of Israel.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 17, 'Dan shall be a serpent in the way, a viper by the path, that bites the horse''s heels so that his rider falls backward.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 18, 'I wait for your salvation, O LORD.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 19, '"Raiders shall raid Gad, but he shall raid at their heels.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 20, '"Asher''s food shall be rich, and he shall yield royal delicacies.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 21, '"Naphtali is a doe let loose that bears beautiful fawns.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 22, '"Joseph is a fruitful bough, a fruitful bough by a spring; his branches run over the wall.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 23, 'The archers bitterly attacked him, shot at him, and harassed him severely,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 24, 'yet his bow remained unmoved; his arms were made agile by the hands of the Mighty One of Jacob (from there is the Shepherd, the Stone of Israel),', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 25, 'by the God of your father who will help you, by the Almighty who will bless you with blessings of heaven above, blessings of the deep that crouches beneath, blessings of the breasts and of the womb.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 26, 'The blessings of your father are mighty beyond the blessings of my parents, up to the bounties of the everlasting hills. May they be on the head of Joseph, and on the brow of him who was set apart from his brothers.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 27, '"Benjamin is a ravenous wolf, in the morning devouring the prey and at evening dividing the spoil."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 28, 'All these are the twelve tribes of Israel. This is what their father said to them as he blessed them, blessing each with the blessing suitable to him.', 'Jacob''s Death and Burial', 'ESV'),
('genesis', 'Genesis', 1, 49, 29, 'Then he commanded them and said to them, "I am to be gathered to my people; bury me with my fathers in the cave that is in the field of Ephron the Hittite,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 30, 'in the cave that is in the field at Machpelah, to the east of Mamre, in the land of Canaan, which Abraham bought with the field from Ephron the Hittite to possess as a burying place.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 31, 'There they buried Abraham and Sarah his wife. There they buried Isaac and Rebekah his wife, and there I buried Leah—', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 32, 'the field and the cave that is in it were bought from the Hittites."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 49, 33, 'When Jacob finished commanding his sons, he drew up his feet into the bed and breathed his last and was gathered to his people.', NULL, 'ESV'),

-- Chapter 50: Jacob's Burial and Joseph's Death
('genesis', 'Genesis', 1, 50, 1, 'Then Joseph fell on his father''s face and wept over him and kissed him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 50, 2, 'And Joseph commanded his servants the physicians to embalm his father. So the physicians embalmed Israel.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 50, 3, 'Forty days were required for it, for that is how many are required for embalming. And the Egyptians wept for him seventy days.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 50, 4, 'And when the days of weeping for him were past, Joseph spoke to the household of Pharaoh, saying, "If now I have found favor in your eyes, please speak in the ears of Pharaoh, saying,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 50, 5, 'My father made me swear, saying, ''I am about to die: in my tomb that I hewed out for myself in the land of Canaan, there shall you bury me.'' Now therefore, let me please go up and bury my father. Then I will return."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 50, 6, 'And Pharaoh answered, "Go up, and bury your father, as he made you swear."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 50, 7, 'So Joseph went up to bury his father. With him went up all the servants of Pharaoh, the elders of his household, and all the elders of the land of Egypt,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 50, 8, 'as well as all the household of Joseph, his brothers, and his father''s household. Only their children, their flocks, and their herds were left in the land of Goshen.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 50, 9, 'And there went up with him both chariots and horsemen. It was a very great company.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 50, 10, 'When they came to the threshing floor of Atad, which is beyond the Jordan, they lamented there with a very great and grievous lamentation, and he made a mourning for his father seven days.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 50, 11, 'When the inhabitants of the land, the Canaanites, saw the mourning on the threshing floor of Atad, they said, "This is a grievous mourning by the Egyptians." Therefore the place was named Abel-mizraim; it is beyond the Jordan.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 50, 12, 'Thus his sons did for him as he had commanded them,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 50, 13, 'for his sons carried him to the land of Canaan and buried him in the cave of the field at Machpelah, to the east of Mamre, which Abraham bought with the field from Ephron the Hittite to possess as a burying place.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 50, 14, 'After he had buried his father, Joseph returned to Egypt with his brothers and all who had gone up with him to bury his father.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 50, 15, 'When Joseph''s brothers saw that their father was dead, they said, "It may be that Joseph will hate us and pay us back for all the evil that we did to him."', 'God''s Good Purposes', 'ESV'),
('genesis', 'Genesis', 1, 50, 16, 'So they sent a message to Joseph, saying, "Your father gave this command before he died,', NULL, 'ESV'),
('genesis', 'Genesis', 1, 50, 17, '''Say to Joseph, Please forgive the transgression of your brothers and their sin, because they did evil to you.'' And now, please forgive the transgression of the servants of the God of your father." Joseph wept when they spoke to him.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 50, 18, 'His brothers also came and fell down before him and said, "Behold, we are your servants."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 50, 19, 'But Joseph said to them, "Do not fear, for am I in the place of God?', NULL, 'ESV'),
('genesis', 'Genesis', 1, 50, 20, 'As for you, you meant evil against me, but God meant it for good, to bring it about that many people should be kept alive, as they are today.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 50, 21, 'So do not fear; I will provide for you and your little ones." Thus he comforted them and spoke kindly to them.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 50, 22, 'So Joseph remained in Egypt, he and his father''s house. Joseph lived 110 years.', 'The Death of Joseph', 'ESV'),
('genesis', 'Genesis', 1, 50, 23, 'And Joseph saw Ephraim''s children of the third generation. The children also of Machir the son of Manasseh were counted as Joseph''s own.', NULL, 'ESV'),
('genesis', 'Genesis', 1, 50, 24, 'And Joseph said to his brothers, "I am about to die, but God will visit you and bring you up out of this land to the land that he swore to Abraham, to Isaac, and to Jacob."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 50, 25, 'Then Joseph made the sons of Israel swear, saying, "God will surely visit you, and you shall carry up my bones from here."', NULL, 'ESV'),
('genesis', 'Genesis', 1, 50, 26, 'So Joseph died, being 110 years old. They embalmed him, and he was put in a coffin in Egypt.', NULL, 'ESV')

ON CONFLICT (book_id, chapter_number, verse_number, translation_code)
DO UPDATE SET verse_text = EXCLUDED.verse_text, section_heading = EXCLUDED.section_heading;
